### ISSUE TITLE
how to fully stop restart simulation

### ISSUE THREAD

**Issue by trebor** [liabru/matter-js#1011]
can someone provide an official set of steps, ideally expressed in code, to fully stop, reset and restart the simulation in such a way that it does not leak memory?  so for i have spent hours on this and am now researching alternative libraries, as this is a show stopper for me.

**Comment by michael-garofalo** [comment]
I don't have any great words of wisdom here, other than to say I don't think it's the library.

https://photics.com/free-template-tuesday-23-tumult-hype-physics/

...that was built with Hype, which uses Matter.js as the Physics engine. The three Physics experiments seem to reset nicely. I don't know how Tumult is doing it, but that seems to suggest that Matter.js might be OK.

What's going wrong exactly? What shows up in the console log? What do the developer tools tell you? If memory is leaking, where's the memory going? In other words, is it JavaScript causing the leaking? Is it the browser "painting" the page? (Are you using large images files?) How are you reseting / restarting the simulation?

**Comment by bouraqadi** [comment]
`worldMatter.Composite.clear(world,false);` Would delete all objects and constraints. 
`true` instead of `false` would keep static objects.
More at https://brm.io/matter-js/docs/classes/Composite.html

**Comment by liabru** [comment]
I think [Engine.clear](https://brm.io/matter-js/docs/classes/Engine.html#method_clear) should handle this fine? 

Otherwise take a look at how the included [examples](https://github.com/liabru/matter-js/blob/master/examples/mixed.js) are built, they include a function to stop the runner and renderer and will create a new engine and scene on every reset.
