### ISSUE TITLE
Objects falling out of borders

### ISSUE THREAD

**Issue by 22092** [liabru/matter-js#1025]
https://codepen.io/celsowhite/pen/XWbEzpx

I found this project and want to use it in my website, but the problem is when I push it very hard, it can fall out of the boundary, I want to know how to prevent it from never falling out of the boundary?

https://user-images.githubusercontent.com/86338011/123035076-4dd6e080-d41d-11eb-8145-321d4a604f36.mp4

**Comment by AurangAsif** [comment]
Thats likely because there is no CCD (see #5).  Your options are:
1. Limit the max speed of objects
2. Make the border walls thicker. You would have to move them outwards as well to prevent it from affecting the inner space
3. Use raycasts
4. Check if objects are out of bounds and teleport them back inside
