### ISSUE TITLE
can not attached image

### ISSUE THREAD

**Issue by Ganjang-chichen** [liabru/matter-js#1034]
I can not add png at Node JS in ejs

> 
>         slime = Bodies.rectangle(100, 100, 96, 96, {
>             render: {
>                     strokeStyle: '#ffffff',
>                     sprite: {
>                         texture: './images/slime.png'
>                     }
>                 }
>         });
>          Composite.add(world, slime);

in canvas, rectangle is built, but it do not be attached png image.
but this code work

> let testimg = new Image();
> testimg.src = "./images/slime.png";
> document.body.appendChild(testimg);

**Comment by liabru** [comment]
Which browser? Could you check the console and network tab to see if there are any errors for this?

**Comment by goodwin74** [comment]
I have a similar problem
`Bodies.circle(50, 50, 6, {
    collisionFilter:{
        category:2,
        mask:4
    },
    label:'mainSph',
    render: {
        sprite: {
            texture: './css/sphere/img/sph.png',
            xScale: 1,
            yScale: 1
        }
    }
});`

After launch, just a circle without texture is displayed. There are no download errors in the console, and there are no attempts to download this resource in the Network tab either.
It seems as if nothing has changed in the scene after adding the texture option

**matter-js 0.20.0**

**Comment by goodwin74** [comment]
I found a solution! I accidentally came across a question related to setting lineWidth for objects, and there was an answer that it works in **wireframes=false**. It turns out that the sprite option also works when the "wireframes" mode is disabled. As soon as I set "**wireframes:false**" in Render, the sprite was drawn.
Considering that the "wireframes" mode is enabled by default, I think beginners should indicate in the documentation (in the description of all Body.render.* options) that they need to set wireframes:false so that they are used by the built-in renderer.
