### ISSUE TITLE
Chamfer options still working? Work once time only?

### ISSUE THREAD

**Issue by YoNeXia** [liabru/matter-js#1059]
Hello,

I want to use the chamfer function to round the corners of the rectangles.
I have several problems when I try to use it.

### My code :
![Object initialization](https://user-images.githubusercontent.com/23256059/140018053-b8387358-9ee9-4663-8c00-25e5e0fd8546.png)

![Create Rectangle function](https://user-images.githubusercontent.com/23256059/140018313-abc45073-9ee3-4a90-8f1e-43edb8d09586.png)

![Rectangles creation](https://user-images.githubusercontent.com/23256059/140018204-8448bd5e-5a56-4986-88b3-187ecce23791.png)

### Issues:
- Cannot find the console option chamfer when displaying my base object. `plinkos_data_2.options` are no displayed the chamfer from my basic object in console. And the rectangles created with `plinkos_data_2.options` have chamfer = null. (But in second part, chamfer is applied... WUT)
![Console logger](https://user-images.githubusercontent.com/23256059/140018674-4f17b0f7-f351-4093-9dd8-dd2500786a40.png)

- The option applied to the first element created with the previous options, but only to the first.
![Render in canvas](https://user-images.githubusercontent.com/23256059/140018814-0f5a82ec-313e-46e2-b255-dcc372448f1c.png)

I’m trying to understand how the chamfer option works, but can't reach it, and I can’t find any help in the documentation.

Thank you.
YoNeXia.

**Comment by liabru** [comment]
That's right `chamfer` is only a special one-time pre-processing option of `Matter.Bodies` rather than a body property. 

This isn't well documented so sorry about that - it's one of the oldest parts of the project that I'd love to move to a plugin or example when I get chance.

You can use [Vertices.chamfer](https://brm.io/matter-js/docs/classes/Vertices.html#method_chamfer`) if you want to apply this in a custom way, but you will probably want to keep a copy of the original input.
