### ISSUE TITLE
Position values change by accessor

### ISSUE THREAD

**Issue by Radnen** [liabru/matter-js#106]
```javascript
			// set up Matter.Engine...

			var once = true, item = null;
			var stack = Composites.stack(30, 30, 13, 5, 0, 0, function(x, y) {
				var rect = Bodies.rectangle(x, y, 40, 10, { friction: 0.05,  density: 0.0001, render: { fillStyle: "red" } });
				if (once) {
					console.log(rect.position);
					console.log(rect);
					once = false;
				}
				return rect;
			});

			// add stack to world and run engine...
```

You'll notice in this example there are two values. The first is an object with x and y at 30 which is correct for it's location. The other reads 51.5 for the x value (in the console if you open the location object). I don't know why it changes the position just by accessing it differently. It makes it hard to get back the exact position I see in the rendered environment. These numbers look off to me.

**Comment by liabru** [comment]
There are two things going on here - one is that expanding an object property in dev tools happens at the time you click it rather than when `console.log` is called.

The second thing is that `Composites.stack` automatically shifts bodies based on their bounding boxes such that they do not overlap, see the [code](https://github.com/liabru/matter-js/blob/master/src/factory/Composites.js#L38-L50).

Together these explain the difference. If you try this again with a single body (not using `Composites.stack`) and you also _do not_ call `Engine.run` then you should get the same position value both times.

See my fiddle for a [demo](https://jsfiddle.net/ms9qdLqa/). Hope that makes sense?
