### ISSUE TITLE
I've updated my benchmark for 3 active js Physics Engines.

### ISSUE THREAD

**Issue by finscn** [liabru/matter-js#1060]
I've updated my benchmark for 3 active js Physics Engines.
This benchmark is very very simple  and basic .
But I think it has already could tell us something .

https://finscn.github.io/phy-benchmark/

**Comment by 8Observer8** [comment]
Asus K53SV; 8 GB RAM, i3 2.2 GHertz (2 cores); Intel HD Graphics 3000; Nvidia Geforce GT 540M (1 GB); Windows 10

- box2d.ts : 27 FPS
![image](https://user-images.githubusercontent.com/3908473/143288186-5398177b-c3d9-4a9b-8986-6d0327281c3b.png)

- planck.js : 17 FPS
![image](https://user-images.githubusercontent.com/3908473/143288430-fb63661e-583a-446a-bb0c-9cbeadea89ba.png)

- matter.js : 43 FPS
![image](https://user-images.githubusercontent.com/3908473/143288683-ad49651c-7cf4-4a18-a465-170dcc8833b1.png)

**Comment by liabru** [comment]
You may want to try this out with [0.18.0](https://github.com/liabru/matter-js/pull/1069) as it should give a nice performance boost. 

Also I think for your `tumblerBox` you might want to use `Body.setAngularVelocity` rather than `Matter.Body.setAngle` since the latter doesn't give the correct collision response when used for movement (unless you also update the velocity manually).
