### ISSUE TITLE
Should this line of code in Runner heed the delta property?

### ISSUE THREAD

**Issue by gotchipete** [liabru/matter-js#1078]
We noticed in our game that setting a `delta` of `1000/30` on our `Runner` had zero effect on the number of updates per second... then found this: https://github.com/liabru/matter-js/blob/master/src/core/Runner.js#L40 ... hardcoded to `1000/60` - is this intended or should it heed the `delta` property?

**Comment by fishmongr** [comment]
This definitely looks like an issue caused by the Runner.delta property not being used by MatterJS when it is run server-side. In this case it creates it's own  _requestAnimationFrame method with hard coded delta 1000/60 since one is not provided by a browser.

**Comment by liabru** [comment]
It's only meant as a basic polyfill for browsers, a fallback for when the browser doesn't support `requestAnimationFrame` (has not been a concern now for many years though).

When running server side, the `requestAnimationFrame` API doesn't make much sense since it is headless. In that case go with your own update loop calling `Engine.update` based on your specific use case.

**Comment by fishmongr** [comment]
@liabru perhaps the docs can be updated to let folks know these Runner features are not currently supported in server-side implementations of matterJS? I understand the provided Runner doc states it's meant for testing and not production but nowhere does it say configuring it just doesn't work when running on a server.
