### ISSUE TITLE
Circles roll down inclined planes at constant velocity

### ISSUE THREAD

**Issue by efunneko** [liabru/matter-js#1158]
I am trying to simulate a ball rolling down a number of inclined planes. I am just creating some simple circles and rectangles with default parameters, but playing around with restitution to get a bit of bouncing. It seems that as soon as the ball stops bouncing and sliding down the slope, it will roll the rest of the way at constant velocity rather than accelerating as it should.

Is there a setting that I might have wrong or is this a physics bug?

Here is a codepen showing it:

https://codepen.io/efunneko/pen/oNdGbVz

**Comment by liabru** [comment]
If you use `render.options.showAngleIndicator = true` then you can see things a bit easier. I think you need to consider friction effects here, which you should experiment with e.g. `body.friction`, `body.frictionStatic` and `body.frictionAir`. 

Also since this is a very short ramp for the size of the ball, there won't be much time for visible acceleration. You can try making it longer and also increasing the gravity scale for that as well as friction.
