### ISSUE TITLE
enum or literal js dictionary for type 

### ISSUE THREAD

**Issue by djmisterjon** [liabru/matter-js#1188]
sup , i have type issue with the type property, am new with this libs.
![image](https://user-images.githubusercontent.com/24865815/209467465-99fe5eeb-adcc-42b6-8b9d-c6601496b15e.png)

can you provide a enum or if your not ts friend,  maybe a literal js object dictionary for all types, or just a collection of literal string ?

because it look like we code blind here ! and the ide cant etablis relation
![image](https://user-images.githubusercontent.com/24865815/209467523-ce7ca549-b6cf-4a37-83d7-aef207730211.png)

thanks 

--- 

i also cant found all type list in the doc ! 
i ask gpt and it give me this, i cant confirm they are all valide because they are not in doc! 
if someone can confirm ? 
![image](https://user-images.githubusercontent.com/24865815/209467797-9c4b6140-3a58-42f7-b367-de80e6469f87.png)

**Comment by liabru** [comment]
The `type` properties are all strings.

I think the current list is `'body'`, `'composite'`, `'constraint'`, `'mouseConstraint'`. These are mostly intended for internal use in `Matter.Composite` rather than strict typing. 

The TypeScript bindings are not native to this project, so you may want to check with the developers who maintain them if that's what you need.
