### ISSUE TITLE
Can sprite.texture be drawed adjust to the bodies shape or size?

### ISSUE THREAD

**Issue by andyforever** [liabru/matter-js#120]
For example,

If I create a body by Bodies.circle(...),and I set the body options like 
```javascript

var options = {render: {
        sprite: {
              texture: '/img/rect_800*600.png'
        }
}}

 Bodies.circle(100, 100, 50, options)
```
Can the texture be drawed in a circular shape and resized to the body's size?

**Comment by andyforever** [comment]
@liabru

**Comment by liabru** [comment]
You can use `body.render.sprite.scaleX` and `scaleY` see [the docs](http://brm.io/matter-js-docs-master/classes/Body.html#property_render.sprite.xScale).

**Comment by andyforever** [comment]
Thanks. I'll have a try.

**Comment by DaveSeidman** [comment]
I had trouble figuring out how to scale textures via the docs, but looking at the code I found the properties I was looking for:
`render.sprite.xScale` and `render.sprite.yScale`
here: https://brm.io/matter-js/docs/files/src_render_Render.js.html#l2166 line #660

The docs link from @liabru is no longer online, a better link may be: 
https://brm.io/matter-js/docs/classes/Render.html#property_textures 
and maybe the scale and offset properties could be exposed so that they appear in the docs.

**Comment by frafra** [comment]
It would be nice to have xScale, yScale, xOffset, and yOffset documented.
