### ISSUE TITLE
Trapezoid with slope=1 did not collide with other objects

### ISSUE THREAD

**Issue by YChebotaev** [liabru/matter-js#138]
```javascript
// Matter.js module aliases
var Engine = Matter.Engine,
    World = Matter.World,
    Bodies = Matter.Bodies;

// create a Matter.js engine
var engine = Engine.create(document.body);

// create two boxes and a ground
var trap = Bodies.trapezoid(400, 10, 80, 80, 1)
var boxA = Bodies.rectangle(400, 200, 80, 80);
var boxB = Bodies.rectangle(450, 50, 80, 80);
var ground = Bodies.rectangle(400, 610, 810, 60, { isStatic: true });

// add all of the bodies to the world
World.add(engine.world, [boxA, boxB, ground, trap]);

// run the engine
Engine.run(engine);
```

http://codepen.io/anon/pen/GJbZyv

**Comment by liabru** [comment]
Do you need a triangle? Use [Bodies.polygon](http://brm.io/matter-js-docs-master/classes/Bodies.html#method_polygon) with sides 3. 

Otherwise, I can't see why you'd want a trapezoid with slope 1 because it doesn't generate a trapezoid. The value should be more like 0 to 0.5, so closing this, thanks.

**Comment by YChebotaev** [comment]
It's a bug and it must be fixed.

**Comment by liabru** [comment]
It's a rare edge case, can you tell me why you need this?
Otherwise, feel free to submit a pull request.

**Comment by YChebotaev** [comment]
I don't actually need this but i was trying to get a triangle with one side shorter and slope=1 gives me figure i was looking for. This is how i find this bug.
