### ISSUE TITLE
Inline SVG sprite

### ISSUE THREAD

**Issue by jonmct** [liabru/matter-js#142]
Im having a great time experimenting with Matter but have been wondering if there is any way to pass an inline SVG as a sprite? Im thinking of manipulating some interactive text but can't really figure out how I would go around doing so.
thanks!

**Comment by liabru** [comment]
The built in renderers do not support SVGs as sprites so your best option is probably to convert them to raster otherwise you will need to create a [custom renderer](https://github.com/liabru/matter-js/wiki/Rendering#using-a-custom-renderer) that can render SVGs.

Alternatively there is support for converting SVGs to bodies which can be rendered (but only in a limited way), see the [SVG demo](http://brm.io/matter-js-demo-master/#svg) and the [source code](https://github.com/liabru/matter-js/blob/master/examples/svg.js).

**Comment by jonmct** [comment]
Thanks for the quick reply!

i will try to figure out a workaround, how about using an animated gif as a sprite, is it in anyway possible? from what I can see it only renders the first frame but the gif is frozen in time for eternity...
cheers

**Comment by liabru** [comment]
No support for that either I'm afraid, the renderers are pretty basic really, esentially just enough for testing. You can [create a custom renderer](https://github.com/liabru/matter-js/wiki/Rendering#using-a-custom-renderer) if you need to extend them.
