### ISSUE TITLE
Examples.js missing

### ISSUE THREAD

**Issue by 17chicken** [liabru/matter-js#161]
Hi guys,

It seems you've got a file missing, and it's essential to get the examples working locally.

demo/js/Examples.js

This seems to be missing from the folder.

Thanks

**Comment by liabru** [comment]
Can you try using `grunt` to build the project? It should compile `Examples.js` for you.

I didn't commit it yet because I wanted to avoid confusion over where the source for the examples is.
I'll commit it soon when I figure how to make this clear, I'll probably put it in a build folder with a header comment.

**Comment by 17chicken** [comment]
Ah, should've seen that. It's working now, thanks for the help.

Great framework by the way.

**Comment by liabru** [comment]
No problem, let's keep this open until I find a way to make it easier.

**Comment by yafp** [comment]
Example.js is still missing in release 0.10.0
