### ISSUE TITLE
Units for Position, Velocity, Acceleration (gravity)

### ISSUE THREAD

**Issue by DZGoldman** [liabru/matter-js#179]
Looking for any information on the actual units that position, velocity, and acceleration are measured in, i.e, if an object is moving at a velocity of 12, is this measuring pixels per millisecond? Especially interested in what the gravity constant represents, unit wise. Thanks.

**Comment by liabru** [comment]
If you use the built in renderer and and built in runner, with default settings:

- 1 position = 1px
- 1 speed = 1px per step
- 1 step = 16.666ms

But ultimately, the units are relative to how you choose to render and interpret that scale.

Gravity is applied like this, every step:

    body.force.y += body.mass * gravity.y * 0.001;
    body.force.x += body.mass * gravity.x * 0.001;

Where `0.001` is a fixed constant scaling factor (note that this may change in future versions).

**Comment by jstoeffler** [comment]
I think the 0.001 factor is confusing.

To have something that made sense to me, I used gravity = 0.981 (to remain close to the original value, while having something familiar) and I kept in mind "100px = 1m".

I think it would be great to have standard units for what can be standard (everything except distances).

That would be:

- position in px
- speed in px/s
- acceleration in px/s^2
- hence force in N and torque in N*px

**Comment by liabru** [comment]
I made a change in a38b227 that moves the gravity constant to `world.gravity.scale`, which means you can now set it to 1 if needed.

Internally the engine uses MKS (meters, kilograms, and seconds) units and radians for angles.
This is the same as Box2D, as described in their [blog post](http://box2d.org/2011/12/pixels/).

It's a bad idea to specify anything in pixels at the engine level because pixels are relative to the engine user's rendering and step size is relative to game loop implementation, which may vary among users. So it's down to the user to define their own scales that fit their purposes. It's best to apply any scaling at render time.

There's more explanation about this in [the Box2D blog post](http://box2d.org/2011/12/pixels/). Hope that makes sense.

**Comment by DZGoldman** [comment]
Thanks, I look forward to checking out 0.9!
