### ISSUE TITLE
lineWidth = 0 actually does nothing.

### ISSUE THREAD

**Issue by rgbjoy** [liabru/matter-js#220]
Since context.lineWidth doesn't take 0

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineWidth

**Comment by liabru** [comment]
Can you explain more about where and why this is a problem? Do you mean you can't disable outlines because of this?

**Comment by codeclown** [comment]
Yes, that is the issue. Can't disable body outline. This goes against the [documentation](http://brm.io/matter-js/docs/classes/Body.html#property_render.lineWidth).

Could be easily fixed by simply checking for 0 [here](https://github.com/liabru/matter-js/blob/e3e90807e8f8496ce80a9b3de49fa582d1294086/src/render/Render.js#L388).

```
if(constraint.render.lineWidth) {
    c.lineWidth = constraint.render.lineWidth;
    c.strokeStyle = constraint.render.strokeStyle;
    c.stroke();
}
```

I'm happy to provide a pull request if you'd like.

**Comment by rgbjoy** [comment]
@liabru 

> A value of 0 means no outline will be rendered.

This isn't currently possible to do.  @codeclown that would do the trick.
