### ISSUE TITLE
Chain Bouncing issue

### ISSUE THREAD

**Issue by sowmyavetrikannan** [liabru/matter-js#272]
Hi,

I am having a chain in my application. In that chain three bodies are positioned with a constraint. I want to change the angle of a single body and then i have to change the sprite texture for that body. After changing angle i gave Engine.run(engine). This makes the chain bouncing continuously. Is there any way  to stop that bouncing?? Thanks in advance..

**Comment by alelavoie** [comment]
I had problems with bouncing chains as well. I solved it by leaving a gap of 1px between the objects edges and the constraint attach points. 

They still bounce when I pull hard enough on them though. I guess the problem is related with the constraint themselves. 

I haven't have the time to check the code in detail yet. Anyone has an idea of what could cause this ?

**Comment by crazyyi** [comment]
@liabru Is this a bug or just not using constraints correctly? Anyway I have this bouncing problem and don't know where to ask my question so I just put it here.

Say I have a chain, with 2 or more bodies attached to one end of the chain. I want it to look like a snake. So I remove the gravity and make it move with my mouse. But when the bodies are too close to each other the bodies are always jumping or bouncing around the head.

My constraint is like:

```
Constraint.create({
		 			bodyA: body,
		 			bodyB: prevBody,
		 			stiffness: 0.3,
		 			length: 12 // body radius is 10
});
```

I am looking into using collision filter to fix this. But all the demos I can find are gravity-based. Hope you can give me some hint.

**Comment by liabru** [comment]
Could do with an example here if anyone can provide. Did you try increasing `engine.constraintIterations`?

**Comment by crazyyi** [comment]
@liabru Maybe my main problem is not related to the bouncing because I can use collision filter to fix that, at least for now. What I get is something like this: https://res.cloudinary.com/dpp1fgy7c/image/upload/v1491312232/game_g5h1lp.gif
But I don't want the bodies to follow the head swiftly, can I make them rotate slowly and do not swing to another direction? You know, move like a snake. I can do that in my own implementation without a physics engine, but I am thinking if matter.js can handle collision detection in a cleaner manner why don't I just use it to do the job?

**Comment by liabru** [comment]
@crazyyi not sure if you still need help on it, but try using the `constraint.angularStiffness` combined with `constraint.damping`
