### ISSUE TITLE
Destructable Terrain?

### ISSUE THREAD

**Issue by daumann** [liabru/matter-js#291]
Starting from the Concave Terrain example, any idea how you would use this library to create destructible terrain as in the Worms games for example?

**Comment by liabru** [comment]
That's a pretty big question as destructible terrain itself is a very big topic with many approaches (one of the best I've seen uses marching squares). You can certainly do it with matter.js (as creating, removing, updating bodies is cheap) but it really depends on the approach you take. 

Can you be more specific about the approach you have in mind? Otherwise this is a bit too big of a question to answer here.

**Comment by daumann** [comment]
Here is an example: https://youtu.be/Qkh8PMwOgQ4?t=34
Is that something which I can implement using the current functions of the library?

**Comment by liabru** [comment]
Yeah sure you could implement this by creating static bodies and changing their vertices. It really depends on your approach though. Check out [JS Clipper](https://sourceforge.net/projects/jsclipper/) project for a start. A triangles / marching squares approach may be more performant though, starting with [earcut](https://github.com/mapbox/earcut) for example.

**Comment by daumann** [comment]
I just came across this [demo](http://www.motions-media.de/developing/cangaja/demo/demo-box2d-5.html) by @samowitsch which also supports rigid body + destructible domain.

**Comment by liabru** [comment]
Nice, looks like they're using the JS Clipper library too, which seems like a good option as you can cut holes of any shape.
