### ISSUE TITLE
cloth / softBody starting height 

### ISSUE THREAD

**Issue by eliteproxy7** [liabru/matter-js#300]
I am trying to create a softBody based cloth just like in the example. everything renders fine. 
My question is how can I have the "cloth" be "rolled" up at the beginning and then drop down 

so it looks like the "cloth" drapes down from the top.

is adding an object that is part of the collision group and then moving it down the only way?

**Comment by liabru** [comment]
Try looping through `cloth.bodies` and then set  `Body.setPosition(body, { x: body.x, y: 100 + gap })`, where `gap = rowGap` when the row number is an odd number otherwise `gap = 0`. In other words, set all of the cloth's particles to be at the same `y` position except add an offset for odd numbered rows.

Hopefully that works and doesn't make the cloth unstable. Otherwise you'll need to write your own which you could base on the source for [Composites.stack](https://github.com/liabru/matter-js/blob/master/src/factory/Composites.js#L35-L73).

**Comment by Phantom180** [comment]
Please help me I a  not able to create the cloth
