### ISSUE TITLE
Triangles unstable?

### ISSUE THREAD

**Issue by staff0rd** [liabru/matter-js#318]
I see the following [here](https://github.com/liabru/matter-js/blob/0bff037f854533e6e9ebd9aa802dd14225408d87/examples/mixed.js#L15);
> triangles can be a little unstable, so avoid until fixed

Is it still relevant?  If so - what's the issue?

**Comment by liabru** [comment]
I've not actually tried them out in a long time, I think they will be much more stable than when I originally wrote that message. Try it out. The stars in the [concave demo](http://brm.io/matter-js/demo/#concave) seem to be pretty good now, so triangles might be ok.

Though, it depends on the type of triangle, as the thing with pointy shapes is that they are hard in general for physics engines and collision detection to handle because they can easily travel straight through other bodies and get stuck. This is related to issue #5 but can be even harder to fully solve.

**Comment by liabru** [comment]
I tried out triangles some more and they seem to be working well, though the comment above about pointy shapes in general is still true.
