### ISSUE TITLE
a falling square wouldn't bounce correctly on a static ground

### ISSUE THREAD

**Issue by kunchenguid** [liabru/matter-js#330]
See http://codepen.io/anon/pen/yVEORO.

A box with 0.3 restitution falling onto a static ground. It should bounce back perfectly vertically, but somehow it doesn't... and currently depending on the size of the ground, the bounce may happen with an angle, or may not happen at all. See the comments in the codepen.

Any thoughts what I might be missing here, or is it a known issue?

**Comment by liabru** [comment]
Thanks for the test case. This is strange because the [Restitution demo](http://brm.io/matter-js/demo/#restitution) seems to work as expected.

**Comment by kunchenguid** [comment]
Yeah really weird.. I didn't figure out where the difference is.

**Comment by liabru** [comment]
I noticed that your demo is using v0.5.0 which is super old, can you try using the latest?

**Comment by kunchenguid** [comment]
@liabru i changed the test case to use master build of matter-js, now it looks even more interesting but unfortunately still not quite as expected...

**Comment by liabru** [comment]
Old thread but I was interested anyway: the ground is far too thin for collisions to work correctly. Also since it the body has a wide shape falling exactly edge-on, the torque forces seem to absorb the collision (in the real world too, think about a rod falling on the ground exactly length on vs edge on). You can ignore this effect by disabling rotation using `inertia: Infinity` on the box, which will make it bounce a lot more.
