### ISSUE TITLE
How to create a shape (sector, cone) like this? Trying to implement range of vision.

### ISSUE THREAD

**Issue by dufia** [liabru/matter-js#344]
![cone-shape_03](https://cloud.githubusercontent.com/assets/5569649/21753388/17a4b938-d5e4-11e6-9b08-3990d4381b63.jpg)

Hey!

I am playing with the library, its awesome! To be precise I am trying to build a relatively simple game prototype. Basicly, a ball that can move around the arena with a range of vision.

So far I managed to create an arena and the ball. I can even control the balls movement but I can't figure out how to implement the range of vision.

I think that I maybe could create a compound body from a ball and a cone shape. The cone shape could detect collisions and appropriately show/hide whatever is in/outside the range. Is this approach fine? If its fine I think I could figure out how to do the rest.

I have one problem though, I have no idea how to draw the cone shape itself. In the picture above I drew an approximation of a shape I would like to get.

Should I use Bodies.fromVertices, if so, how to generate the vertices? Any tips very much appreciated.

Or maybe I should draw my own SVG and use Svg.pathToVertices? If so, what kind of software do you recommend to draw my own SVG?

**Comment by liabru** [comment]
> Is this approach fine? If its fine I think I could figure out how to do the rest.

Yeah, sounds pretty reasonable.

> I have one problem though, I have no idea how to draw the cone shape itself.

My suggestion is to copy the code for [Bodies.Polygon](https://github.com/liabru/matter-js/blob/master/src/factory/Bodies.js#L145-L177) and then changing `theta = 0.8 * Math.PI / sides`. So long as your field of vision is less than a half-circle this should work (as otherwise the body goes concave which needs special handling).

> Or maybe I should draw my own SVG and use Svg.pathToVertices? If so, what kind of software do you recommend to draw my own SVG?

If you're using SVG I suggest that you hand code it as this will keep it simple. Though, you could probably get away with using Inkscape or Illustrator. Just remember that `Svg.pathToVertices` is currently a little hit-or-miss and you sometimes have to coax your SVGs into working by fiddling with them a bit.

**Comment by dufia** [comment]
Thank you mate, Bodies.Polygon solution worked out great 👍
