### ISSUE TITLE
I don't understand why is the far right rectangle reporting collisions with the triangle.

### ISSUE THREAD

**Issue by dufia** [liabru/matter-js#346]
![screen shot 2017-01-11 at 14 58 51](https://cloud.githubusercontent.com/assets/5569649/21853363/b6dfb418-d80e-11e6-9618-3540d7feadbc.png)

**## Here's the fiddle https://jsfiddle.net/1h20r0g9/4/**

Obviously it has to do something with the bounds but I don't know why. Events.on(engine, 'collisionActive', (event) => {}) reports the bodies as being collided. 

The weirdest thing is, the behaviour is correct if the bodies approach each other from a different side (from top or from bottom).

**Comment by liabru** [comment]
Ha! So this is an interesting edge case. It's happening because the collision system reuses old collisions when bodies are moving very slowly or at rest (for performance). 

But here since you're directly setting the position of the range finder, it never has any velocity. Since the wall also has no velocity either, the collision system just keeps reusing the first initial collision as it assumes there's no movement. But there is.

So what you need to do is first set `isStatic: true` on the range finder, then just after you set its position in the tick event, you also need to set its velocity too (exactly like in the [manipulation](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js#L51-L55) example). 

But, if we set its real velocity (i.e. the same as the ball it is fixed to) we still get the same failure as above, because the ball can (legitimately) move really slowly.

A quick solution here is to just set a fake, constant, large velocity on the range finder. This velocity won't have any visual effect if you make it a static body (which you should). Like this:

```js
Body.setPosition(rangeFinder, newVector);
Body.setAngle(rangeFinder, hostAngle);
Body.setVelocity(rangeFinder, { x: 1, y: 0 });
```

This seems to solve it for me. But this does highlight an issue with the collision reuse system, so let's keep this thread open as this is a good example of the problem (thanks for providing it).

**Comment by dufia** [comment]
Thank you very much for a quick fix mate. I can get back to having fun with the library :)

**Comment by adamschwartz** [comment]
@liabru thanks! Is the issue [seen here](https://cdn.rawgit.com/adamschwartz/9378d38ffbaa0a48abb6959b69379a01/raw/45b1c3a0e4b3bd1054d4233f1f15edbac6a5c83f/matter-js-set-position-issue.html) fundamentally the same? If not please let me know and I’ll open up another.

**Comment by liabru** [comment]
The latest release [0.18.0](https://github.com/liabru/matter-js/pull/1069) should resolve issues relating to collision reuse, closing as I'd expect that includes this one.
