### ISSUE TITLE
Engine doesn't seem to do any sort of octree testing before checking collision events

### ISSUE THREAD

**Issue by TrentWDB** [liabru/matter-js#351]
In the game I'm working on I have quite a few objects in the level, enough to make the game lag. They're spaced out so that you can't see all of them in a single frame of reference in the game.

The engine.update call was taking around 8 milliseconds to complete. I noticed that on smaller levels it was taking significantly less time, around 4 milliseconds. This shouldn't be happening (to this degree) in a physics engine as far as I know.

To fix this, I added a variant of octree testing cull all nearby static objects for each non static objects in the world. I then cleared the world of static objects, and added back in only the culled parts of the level that have a possibility of colliding with the non static objects in the world. After doing these operations the engine update call took around 0.15 milliseconds as opposed to the old 8 milliseconds.

**Comment by liabru** [comment]
I've recently noted some lag due to the broadphase too, I'll investigate this. 

Though it does depend on how your world is set up. Large bodies will always be pretty inefficient when using a grid broad phase. Bodies that can't be reached can be culled, but this is a rather advanced optimisation that should normally be implemented per-game depending on the mechanics of the game.

I'm considering to switching to [box-intersect](https://github.com/mikolalysenko/box-intersect) as the author shows some impressive [benchmarks](https://0fps.net/2015/01/23/collision-detection-part-3-benchmarks/). Though, he doesn't show multi-frame benchmarks which is arguably more important.

**Comment by TrentWDB** [comment]
The reason may be that I have large polygon objects in my level. My filtering code maps every object to cells in the world based on their polygon, so having a giant polygon as opposed to smaller parts allows my thing to still optimize correctly. Since it sounds like everything in the engine uses bounding boxes I expect this is why I saw such an increase in performance.
