### ISSUE TITLE
Move body in composite to position not by vector

### ISSUE THREAD

**Issue by liam-b** [liabru/matter-js#362]
Hey, I was just poking through the docs and I can't seem to find anything on moving a composite **to** a position and not **by** a vector. Just wondering if its possible. At the moment i'm just moving the individual body from inside the composite but there must be a better way. Also if there is a way to rotate **to** an angle that would be great.

**Comment by liabru** [comment]
To move a composite to a position you need to define some `origin` on the composite as a reference (usually top left or the center of the bounds of all bodies). Then to move the composite to a `position` you find the vector `position - origin` then you translate the composite (and the origin) by that. The same idea applies for rotation.

**Comment by kittykatattack** [comment]
Help!
I don't understand this explanation 🙃 

I have a Composite that I want to move to a world position of x: 100 and y: 100.
This code does not work, because (as expected) it shifts composite 100 pixels to the right and 100 pixels up.

    Composite.translate(car, { x: 100, y: 100 });

Can anyone explain how I have use `translate` to move the composite to the world position?

Thank you! 🙏

**Comment by kittykatattack** [comment]
I figured it out!

```
let targetX = 100,
     targetY = 100;

Composite.translate(car, { x: -(currentX - targetX), y: -(currentY - targetY) });
```
