### ISSUE TITLE
Bodies do not respond to gravity changes after being loaded

### ISSUE THREAD

**Issue by howardrj** [liabru/matter-js#369]
Hi! I've been experimenting with saving and loading world configurations and noticed something I thought seemed odd. When a configuration is saved to local storage (by clicking the save button on the generated GUI from matter-tools.gui.js) and then loaded again, the bodies no longer respond to changes in either x or y components of gravity. 

I can also reproduce this issue on the demo page (http://brm.io/matter-js/demo/).
Any idea what's going on?

Thanks in advance!

**Comment by liabru** [comment]
I think it's because loading a new world also includes the original gravity settings, while the GUI maintains the reference to the old gravity object which is no longer used by the engine.

I'd say to log an issue on `matter-tools` about this, but don't because the GUI no longer includes the world save / load feature (though, I plan to [add it to MatterTools.Demo](https://github.com/liabru/matter-tools/issues/2) eventually).

**Comment by kmorris1077** [comment]
What's the point of having this editor if you can't load and save worlds?

**Comment by liabru** [comment]
It's helpful for debugging and testing. It's not quite a world editor yet but I'd like it to be. I took the loading and saving out from the tool because it needed more work to be compatible with plugins. But the code still exists if you want to use it, check out [MatterTools.Serializer](https://github.com/liabru/matter-tools/blob/master/API.md#serializer).

**Comment by kmorris1077** [comment]
Will do. Thanks much!
