### ISSUE TITLE
Add damping parameter to constraints

### ISSUE THREAD

**Issue by liabru** [liabru/matter-js#425]
Currently constraints have a stiffness parameter but they do not have a way of setting a damping factor like conventional springs do.

References for implementation:

- https://stakes.github.io/framerplayground/
- http://box2d.org/files/GDC2011/GDC2011_Catto_Erin_Soft_Constraints.pdf
- http://gafferongames.com/game-physics/spring-physics/

**Comment by Rheeseyb** [comment]
Excellent!

I was looking into the constraints code and saw that it is updating the velocity directly, rather than applying a force to the body. Does this imply that you'd be doing the same thing with damping? The reason I ask this is because in doing so it means the mass of the body isn't taken into account, and I have found that to be a pretty important factor when fine tuning DHO springs.

I've (very recently) written a DHO springs plugin for matter-js, which works by applying the compounded force on the body. It is pretty rough around the edges (since it should be adding springs via `World.add(world, spring)`), but if you're interested in taking a look I have just opened the repo [here](https://github.com/momentumworks/matter-springs)

**Comment by liabru** [comment]
I've implemented basic constraint damping, you can try it out now in the constraint-fixes branch [build](https://github.com/liabru/matter-js/tree/constraint-fixes/build). To use it make your constraint soft by setting `constraint.stiffness = 0.1` and then set the damping `constraint.damping = 0.1`. When moved a connected body should return very slowly to a rest position.

> I was looking into the constraints code and saw that it is updating the velocity directly, rather than applying a force to the body. Does this imply that you'd be doing the same thing with damping? The reason I ask this is because in doing so it means the mass of the body isn't taken into account, and I have found that to be a pretty important factor when fine tuning DHO springs.

Don't worry, the constraint-fixes branch now should correctly take mass into account!

> I've (very recently) written a DHO springs plugin for matter-js, which works by applying the compounded force on the body. It is pretty rough around the edges (since it should be adding springs via World.add(world, spring)), but if you're interested in taking a look I have just opened the repo here

Hey that's pretty cool actually, good work. You should extend `Matter.Composite` though rather than world since that is the base class.

Try out my implementation if you can, tell me if it suits.

**Comment by liabru** [comment]
Closing as this was implemented as of `0.13.0`, thanks!
