### ISSUE TITLE
Parent checking

### ISSUE THREAD

**Issue by oliverbenns** [liabru/matter-js#486]
I want to add some custom properties to a body I created with `Bodies.rectangle`. However when I add it to the world, I get the warning of: `Composite.add: skipped adding a compound body part (you must add its parent instead)` from [here](https://github.com/liabru/matter-js/blob/63b02cfbeebe93d28082504f5e89e93f98739743/src/body/Composite.js#L88)

Would it be better to compare the parent by some other means, maybe the id rather than the reference?

This is my code:
```
class Rectangle {
  constructor() {
    this.debugger = new Debugger();

    const matterBody = Bodies.rectangle(...arguments);
    Object.assign(this, matterBody);
  }

  update() {
    this.debugger.update(this.vertices);
  }
}
```

**Comment by Qriva** [comment]
but what exactly is the problem here? and why you get composite parent error?
Also did you try [this](https://github.com/liabru/matter-js/wiki/Creating-plugins#patching)?

**Comment by liabru** [comment]
You can fix this by setting `this.parent = this` after you use `Object.assign`. Though, that said I would not recommend extending bodies in this way. As @Qriva mentioned the recommended way is to use the plugin approach.

So rather than wrapping the body object with another, all you should do is:

`matterBody.plugin.debugger = new Debugger()`

For reference, the `body.plugin` object is specifically for adding custom properties!
