### ISSUE TITLE
Modify movement of objects when colliding with sensor.

### ISSUE THREAD

**Issue by mako1131** [liabru/matter-js#496]
Hello, looking for an advice.
Imagine stairs like in this image: [HLD]( https://steamuserimages-a.akamaihd.net/ugc/272840175074264975/8B0171CAE17FA2CCDACC2A2D509AA290FF33CA37/ )
What I managed to achieve is when the player goes down the stairs and holds only right button, he moves diagonally - right and also down, at 45deg angle. When he leaves the stairs area, he continues straight right. 
In my case, the stairs area is just sensor and I just modify the velocity vector of the player. 
But what I struggle to do is when player pushes some box onto the stairs. I also want this kind of movement to apply on the box. As long as the box is in the stair area, and something moves it in the horizontal direction, it should also move down (or up) with the same speed as it is beeing moved horizontally. 
Tried different approaches but non of them seemed to work as I expected.  What approach would you recommend? Should I manipulate velocity vectors or rather add force?

**Comment by liabru** [comment]
Interesting question. Honestly you're kind of on your own for this type of thing as far as anything built in goes, since it's pseudo 3D, by that I mean it will take a bit of trickery. As you're doing, put a sensor over the stairs area and then apply a function that maps the velocity of bodies in contact to follow a triangle path. Can you show a jsfiddle of what you have?

**Comment by mako1131** [comment]
Something like [this](http://jsfiddle.net/0aneo9b5/2/). 
You can move the player using WSAD keys. Try to walk on the stairs just with the player - this works ok. Then try to push the big box on the stairs.

**Comment by nstolpe** [comment]
I [forked your code](http://jsfiddle.net/mx1noLjc/5/) and made some changes that might be in the direction you're after. I added a `isCollidingWithPlayer` and made the box only move if that and `isCollidingWithSensor` return true. This will keep it from moving if it's on the sensor and the player is moving around somewhere else. There's also a check to see if the player's colliding with the sensor too. If that's the case, the `vec` var already has the right data to update the box. If not, just update the box with the same calculations used to get `vec`. Using `setVelocity` for the box instead of `applyForce` seems to keep things a little smoother, and halving the x and y components of the velocity made for a less drastic speed jump when moving on to the sensor. Hope this helps.

**Comment by liabru** [comment]
Oh hey that's pretty good @nstolpe thank you for helping out!

**Comment by nstolpe** [comment]
@liabru no problem, glad to be able to. Thanks for making Matter, I just started using it last week after I decided rolling my own JS physics system was taking far, far too long.
