### ISSUE TITLE
Slowing down individual bodies with timescale

### ISSUE THREAD

**Issue by christos00** [liabru/matter-js#510]
Hi, 
I'm trying to use the body.timeScale property to slow down a single body that has no force applied to it - a force is applied at the beginning of the animation and the body just drifts (no friction).

However, I found that the velocity is calculated like so `body.velocity.x = (velocityPrevX * frictionAir * correction) + (body.force.x / body.mass) * deltaTimeSquared;` which means that if body.force.x is 0 then the deltaTimeSquared that takes body.deltaTime into account will have no effect. 

Am I misunderstanding something? 
If I am alone in this (since I am developing a psychological  experiment with weird physics) can you suggest any workaround?

Thanks

PS: Amazing work liabru - and I've used many physics engines over the years.

**Comment by liabru** [comment]
Can you give me a little example of how you are creating and moving the body?
Are you setting the body to have 0 friction and setting velocity directly, rather than using a force?

If this is the case, then you just need to multiply the `body.timeScale` with the velocity vector you are setting? I guess this raises the point that maybe `Body.setVelocity` should do this for you?

> PS: Amazing work liabru - and I've used many physics engines over the years.

Thank you!
