### ISSUE TITLE
Inaccurate behavior with high angularStiffness on constraints

### ISSUE THREAD

**Issue by Twosies** [liabru/matter-js#515]
When setting a high angularStiffness, constraints behave appropriately in a vacuum, but when you mix them with external collisions/gravity, they behave oddly. This is most apparent with Angular Stiffness >= 0.999, but I suspect it's a less-visible issue at all stiffnesses > 0.

You can reproduce this by running the Chains example, and modifying the chain links to all have AngularStiffness: 1, like so:

`Composites.chain(ropeA, 0.5, 0, -0.5, 0, { stiffness: 1, length: 2, render: { type: 'line' }, angularStiffness: 1 });`

Most of the links remain angularly rigid, as you'd expect.  But any of the links that touch other bodies seem to ignore their angularStiffness when solving their velocity.  Also, although the constraints are rigid, gravity isn't applied correctly on all of the bodies.  I was able to set up this situation:

https://i.imgur.com/MWbbymf.png

 All of the bodies are resting in place, like it's stable.  If I pick it up and drop it, the whole thing will fall and just land like that again.

I may or may not have run into this while investigating how to implement angle limits on constraints ;)

**Comment by liabru** [comment]
Angular stiffness is a bit of a tuning factor rather than a feature, it's mostly there to improve stability in cases where you have a complex constraint system that's a bit wobbly. In those cases, I'd only expect it to work reasonably for small values, say 0.1 to 0.5.

If you set it to 1, then you will not get any torque applied at all and weird things will happen. I've personally not needed used it in a while, since the constraint solver is much better than it used to be.

Do you have a particular use case where angular stiffness is useful?
