### ISSUE TITLE
Concave Body.velocity Issue in 'collisionStart' Event

### ISSUE THREAD

**Issue by MaLuci** [liabru/matter-js#537]
Firstly, thanks for a really cool engine.

I'm having an issue accessing a body's velocity in the example below. The velocity vector of the body is returned as {0,0} while it is actually non-zero values when logged in the animation loop. This behaviour only occurs when using a concave body; for ex. it works fine if I replace the concave body with a circle body.

```
Matter.Events.on(engine,'collisionStart', function(event)       
    var pairs = event.pairs;
    for(var i=0; i<pairs.length; i++) {
        console.log( pairs[i].bodyB.velocity);
     }
});
```

The concave body:

```
var starvertices = Vertices.fromPath('50 0 63 38 100 38 69 59 82 100 50 75 18 100 31 59 0 38 37 38');
this.body = Bodies.fromVertices(_x, _y, starvertices, {
   render: {
                fillStyle: color,
                strokeStyle: color,
                lineWidth: 1
            }
}, true);
```

Help would be greatly appreciated.

Thanks.

**Comment by liabru** [comment]
Assuming you need the velocity of the parent body, note collision events pairs are given for each part, so in that case this would be `Body.getVelocity(pairs[i].bodyB.parent)`. 

Note if you need the actual velocity of a part rather than the parent body, you'll need to also account for the part's offset from the parent body position as well as the parent body's angular velocity too.

I've also updated the docs on parts to help make this distinction a bit clearer, thanks.
