### ISSUE TITLE
The events "collisionStart" & "collisionEnd" don't give an array with pair data.

### ISSUE THREAD

**Issue by rgk** [liabru/matter-js#579]
So I first started testing with collisionStart and collisionEnd because my general idea is less calls the better. I didn't see pair data but when I use collisionActive I got exactly the data I needed.

If it is a bug: Have collisionStart & collisionEnd give the same data as collisionActive.

Example: https://jsfiddle.net/pnpywa6z/4/ (check the console for output)

Using 0.14.1

**Comment by liabru** [comment]
Try making a clone of `event.pairs` like this:

```
    Events.on(engine, "collisionStart", function(event) {
        console.log('start: ', event.pairs.slice());
    });
    
    Events.on(engine, "collisionEnd", function(event) {
        console.log('end: ', event.pairs.slice());
    });
```

I think the issue is that the `event.pairs` array is being reused somehow so when you expand `console.log` you're seeing a different version to when you first logged it.

So the above should work, I realise it's not obvious so I will mark this as improve.
