### ISSUE TITLE
compound objects

### ISSUE THREAD

**Issue by meandavejustice** [liabru/matter-js#58]
Hello, I'm having a bit of trouble finding the correct way to implement what would essentially be a compound object.

[example from p2.js](http://schteppe.github.io/p2.js/demos/compound.html)

My initial thought was to try and accomplish this via Composites. Another way to describe what I am looking to do would be to have a way to control a group of bodies, with much of the functionality which the Body class has.

for instance:

``` javascript
var sideA = Bodies.rectangle(400, 100, 200, 1, {groupId: 1, isStatic: true});
var sideB = Bodies.rectangle(560, 185, 200, 1, {groupId: 1, isStatic: true});
Body.rotate(sideB, 19.8);
var sideC = Bodies.rectangle(245, 185, 200, 1, {groupId: 1, isStatic: true});
Body.rotate(sideC, 30.4);
var sideD = Bodies.rectangle(245, 360, 200, 1, {groupId: 1, isStatic: true});
Body.rotate(sideD, 19.9);
var sideE = Bodies.rectangle(400, 450, 200, 1, {groupId: 1, isStatic: true});
// flat
var sideF = Bodies.rectangle(552, 370, 200, 1, {groupId: 1, isStatic: true});
Body.rotate(sideF, 30.3);

// I wanna rotate and control the entire group of bodies like this
Body.rotate([sideA, sideB, ... sideF]);
```
Not asking for this api, this is just the best way I can describe the functionality I am trying to achieve.

Could you please point me in the right direction?

**Comment by liabru** [comment]
This isn't currently supported I'm afraid. Though it is something that will hopefully be possible once I have implemented concave polygons [(see this issue)](https://github.com/liabru/matter-js/issues/15), since there will be support for multiple hulls.

Until then, the best you can do is use stiff constraints and composites. If you use the latest edge build, there are also functions for manipulating composites as a group (e.g. [Composite.rotate](http://brm.io/matter-js-docs-master/classes/Composite.html#method_rotate)).

I'll keep this issue open until I've implemented these for real, thanks.

**Comment by meandavejustice** [comment]
Thanks for the quick response, I will give the edge build a shot.

**Comment by liabru** [comment]
These are now supported in the [compound-concave](https://github.com/liabru/matter-js/tree/compound-concave) branch.

You can also try them out in this [demo](http://brm.io/matter-js-demo-master/#svg).

Hopefully these should be merged into master soon!

**Comment by liabru** [comment]
This feature has been merged into master. 
Please open new threads for new issues found, thanks!

**Comment by lafkpages** [comment]
The demo link doesn't work (404)
