### ISSUE TITLE
Force needed to have a body reach a velocity in one update step

### ISSUE THREAD

**Issue by hexus** [liabru/matter-js#603]
Hey there! This is just a question, not an issue with the library.

I've been using MatterJS with Phaser 3 recently and I'm really enjoying it. Something that's eluding me, however, is the force that's required to be applied in order for a body to reach a specific velocity.

Using an impulse as an example, I will use `applyForce` equivalently to the following:

```js
force.x = intendedVelocity.x;
force.y = intendedVelocity.y;
force.scale(body.mass * engine.world.gravity.scale);
object.applyForce(force); // equivalent to Body.applyForce(body, body.position, force);
```

With gravity disabled and no friction of any kind, applying this impulse with a intended Y velocity of `-8` for example, leads to a velocity close `2.222` recurring.

After experimenting (`8 / 2.222`), I noticed that scaling the force by `3.6` exactly leads to my intended velocity.

```js
force.scale(body.mass * 0.0036);
```

Would this simply be down to the `delta` Phaser supplies (which is fixed, and should be `1 / 60`), or is this something specific to a unit of measurement in MatterJS that I don't know about?

Cheers!

**Comment by hexus** [comment]
A friend of mine helped me work out that this is cancelling out the delta time squared used in the verlet integration. Some related issues that helped were #240 and #179.

I still want to make sure that what I'm doing here is sensible though - I am indeed using these velocities to control the forces I'm applying to bodies.

**Comment by liabru** [comment]
>  is the force that's required to be applied in order for a body to reach a specific velocity

Quite a tricky question to solve directly in practice! Not just the math (you need to account for mass, gravity, friction, time etc), but also because of the variability in the engine and the accuracy of the integrator. 

My main suggestion is to avoid using forces when you need precise control, instead set the velocity directly if possible, even if it means faking things (e.g. using some tween function to fake the acceleration). If you must use forces, trial and error and manual tweaking is usually the way forward, I've found.

**Comment by hexus** [comment]
Ah, okay. The main reason I'm using forces here is so that setting velocity directly won't impact the application of any other forces. But that, as you said, means I have to then deal with those forces in my own calculations.

Thanks for the insight here.
