### ISSUE TITLE
[SUGGESTION] Cache vertex-count of poly body for performance.

### ISSUE THREAD

**Issue by finscn** [liabru/matter-js#614]
In common ,  
```
var len = arr.length;
for (var i=0;i<len;i++){ ...}
```
is faster than  
```
for (var i=0;i<arr.length;i++){ ...}
```

Of course ,  In most cases , it's not the performance hotspot . 
But in Physics Engine , it will be called so many times.
And I see there are many  `for (var i = 0; i < vertices.length; i++) {` will be called in one tick.

So I suggest that add a property `vertexCount` to body for caching the vertex-count.
(like box2d)

**Comment by finscn** [comment]
@bchevalier , I see you use these code for loop-vertices in `Vertices.contains`
```
for (var i = vertices.length - 1; i >= 0; i--) {
```
it's better than  i=0 to vertices.length , but why don't you use the code to 
`Vertices.rotate` & `Vertices.translate` etc. ?

**Comment by finscn** [comment]
@bchevalier  , another question : 

Do you try to cache the normal of each side of poly-body ? 

the normal of side doesn't changed when the polygon be moved or rotated .
So if cache `normal of side`  , it could improve the performance when run SAT.

**Comment by bchevalier** [comment]
Are you sure of what you are suggesting?
The performance gain may not be true anymore, see https://mrale.ph/blog/2014/12/24/array-length-caching.html. Reading through the article give a sense that this kind of optimization may well depend on your JS compiler and the setting of the loop.

We could try out the performance gain by modifying all the loops across the whole code base. I am afraid it would be difficult to benchmark otherwise. My intuition was that the performance difference would be so small that it still won't be noticeable (I may be wrong). We may need to optimize the engine much further before this kind of optimization becomes measurable significant.

**Comment by finscn** [comment]
but  Why do you use
```
for (var i = vertices.length - 1; i >= 0; i--) {
```
instead of 
```
for (var i = 0; i < vertices.length; i++) {
```
?
the reason is not  'improving performance' ?

**Comment by bchevalier** [comment]
I do not know. I am either not responsible for that or there is a good algorithmic reason (objects need to be iterated in reverse order).

**Comment by photonstorm** [comment]
@bchevalier agreed, stuff like caching the array length is pointless with modern VMs and has been for years (unless you're manipulating the array size within the loop of course!)

**Comment by finscn** [comment]
got it.
