### ISSUE TITLE
100+ non-colliding objects

### ISSUE THREAD

**Issue by florinpop17** [liabru/matter-js#616]
Hello!

Is there a way I could create more than 100 objects which won't collide with each other, but only with the surrounding environment? Something like I've done [here](https://codepen.io/FlorinPop17/full/OZXrJG) but using matter.js?
As far as I read the docs, you can only have up to 32 collision groups.

Thank you!

**Comment by liabru** [comment]
I think you can use `let group = Body.nextGroup(true)` to get a non-colliding group, then set `body.collisionFilter.group = group` of your 100 bodies to that same `group`?

**Comment by florinpop17** [comment]
Awesome! it worked! All the bodies which are in that group aren't colliding.
Out of curiosity, could you explain why it's still colliding with the walls? (it's the expected behavior, but I was wondering how the system works) 😄

**Comment by AndrewBrownK** [comment]
@florinpop17 you can find the information in the documentation here http://brm.io/matter-js/docs/classes/Body.html#property_collisionFilter

The properties you're looking for are `body.collisionFilter`, `body.collisionFilter.category`, `body.collisionFilter.group`, and `body.collisionFilter.mask`

In short (if I understand and explain correctly): 

 - Category is a number. If two bodies have the same positive category number, they always collide. If they have the same negative category number, they never collide (these are your 100 objects). Otherwise we check the group and mask (your walls have no group, so your walls fall under this 'otherwise' situation. See next bullet point).

 - The group and mask are bit sets. Each body belongs to one single collision group (one bit in the group bit set), and collides against any other body in a group that collides with the mask (any number of bits in the mask bit set). The default setting for the group and mask of every body is to collide with everything (this is why your walls collide with the 100 objects).

**Comment by liabru** [comment]
Yeah I think that's pretty much it, thanks @AndrewBrownK. To be fair, I'm not a huge fan of the approach and there's a discussion around making it better in #341.
