### ISSUE TITLE
How I can stop a body after I stop applying a force?

### ISSUE THREAD

**Issue by ellipticaldoor** [liabru/matter-js#621]
Right now I'm using **applyForce** to move an object. This object is a character in a game and I want to stop the character as soon the key for moving is released, now the object has inertia and keeps moving.

This is how I'm creating now the body
``` js
const makeBody = (x, y) => {
	const body = Bodies.rectangle(x, y, tileSize, tileSize, {
		inertia: Infinity,
		friction: 0,
		frictionAir: 0.1,
	})

	World.add(physics.engine.world, body)

	return body
}
```

And this is how I apply the force
```js
const moveEntity = (delta, body, force, dirX, dirY) =>
	Body.applyForce(body, body.position, {
		x: dirX * force * delta,
		y: dirY * force * delta,
	})
```

Any ideas or examples?

If instead of using **applyForce** I just update the body position what happens is that the character now can cross static bodies.

**Comment by liabru** [comment]
When controlling something like this, I always suggest avoiding using forces for the most part, instead control the objects position exactly as in the [body manipulation demo](http://brm.io/matter-js/demo/#manipulation) and the [source](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js). There are also ways to combine forces and this approach, you'll need to experiment. Sometimes you could even use constraints since they offer lots of control. See also discussions in #320, #334 and #157.

**Comment by fellow0011** [comment]
if you want to stop a body by applying 1 opposite force to it, you should apply a force equivalent to the body's velocity times it's mass divided by the deltatimestep squared.
`Matter.Body.applyForce(body,{`
	x:body.position.x,
	y:body.position.y
	},{
	x:-1*(body.velocity.x*body.mass)/Math.pow(runner.deltaMin,2),
	y:-1*(body.velocity.y*body.mass)/Math.pow(runner.deltaMin,2)
})`
