### ISSUE TITLE
The gravity performance of formal packages and dev packages is inconsistent under constraint conditions.

### ISSUE THREAD

**Issue by 1977474741** [liabru/matter-js#653]
Code here, if you want to see the dev version of the effect, the configuration of the matter official package can be deleted.
Using a formal package is like no gravity.
https://codepen.io/_undefined/pen/oPYoNb#code-area @liabru @sethvincent @mrspeaker @Rantanen

**Comment by 1977474741** [comment]
![gif](https://user-images.githubusercontent.com/22722580/44895238-0fc91900-ad26-11e8-88ff-74d389e2ce36.gif)

**Comment by 1977474741** [comment]
![gif](https://user-images.githubusercontent.com/22722580/44895412-d93fce00-ad26-11e8-9514-964ef90a1d49.gif)
This is the dev package used, which is normal.

**Comment by liabru** [comment]
Can you please link to the two exact builds used please?

**Comment by 1977474741** [comment]
The official package is 0.12.0, dev package. I don't know which version it is. I downloaded it in your official demo.

**Comment by liabru** [comment]
The latest version is [0.14.2](https://github.com/liabru/matter-js/tree/master/build), does that one work correctly for you? The [car demo](http://brm.io/matter-js/demo/#car) is using that version and seems to work fine?

**Comment by Rantanen** [comment]
I have no idea how I ended up mentioned in this issue, but anyway. Here is the code behind the codepen link running against Matter 0.12.0 and Matter 0.14.2:

- [Matter 0.12.0](https://jubjubnest.net/~wace/matter-653/matter-0.12.0.html)
- [Matter 0.14.2](https://jubjubnest.net/~wace/matter-653/matter-0.14.2.html)

Seems 0.12.0 had an issue that has since then been fixed.

**Comment by 1977474741** [comment]
@Rantanen Thank you. 0.14.2 is OK.

**Comment by 1977474741** [comment]
@liabru  Thank you. 0.14.2 can work normally.
