### ISSUE TITLE
Can anybody guide me to a resource on using the keyboard to manipulate a body?

### ISSUE THREAD

**Issue by mutant-city** [liabru/matter-js#671]
I know this isn't a true issue per say but just wondering if there's any docs/demos on how to use the keyboard to manipulate a body?

**Comment by liabru** [comment]
There isn't an example for this but you can listen to keyboard events on the window, or use a keyboard library (for example [keymaster](https://github.com/madrobby/keymaster)) and then move the body around as in the [manipulation](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js) example.

**Comment by ggorlen** [comment]
If you add a listener to the keyboard event on the window, you'll probably want to add a layer of indirection before using that to apply forces on bodies as shown in [Movement is jerky in matter.js](https://stackoverflow.com/questions/68416755/movement-is-jerky-in-matter-js/68425122#68425122) on Stack Overflow. Otherwise, your operating system's key retrigger can get in the way of smooth movement you'd usually expect from holding a key down in a game.
