### ISSUE TITLE
Too many collisions makes constraints "sag"

### ISSUE THREAD

**Issue by FieryLionite** [liabru/matter-js#682]
I'm making a digestion simulator, the GI linings are made from chains. Normally, they hold together well:
![bug1](http://i64.tinypic.com/28t9p91.png)
But when there are a lot of object colliding with each other, all constraints in the game would sag like this, until the collisions stop. I simulated the collisions with a few dozens objects offscreen
![bug1](http://i67.tinypic.com/2ngrccz.png)

**Comment by liabru** [comment]
Try increasing `engine.constraintIterations` that might help, though there will always be some sag unless you decrease stiffness slightly along the chain to make it appear more even.

**Comment by nasenfloete** [comment]
@liabru 
Same Question, but with boxes, i want to stack boxes on top of each other, without saggin in (like it would be in the real word) it works for a small number of boxen (Count=10) but the more boxes are stacked, the more the "sagging" appears. Can be tested here:
https://codepen.io/lukasdue/pen/QYzxXE

Is there a parameter I need to change in order to prevent this? I already tried density and increasing `engine.constraintIterations`

**Comment by MangoLion** [comment]
> **Edit**: Solved it through increasing this values damatically:

You're awesome! I've literally been stuck on this problem for a year. Increasing the iterations stopped the sagging, though it also reduce my FPS to 1/10 but thats another problem that I can fix

**Comment by FieryLionite** [comment]
> **Edit**: Solved it through increasing this values damatically:

You're awesome! I've literally been stuck on this problem for a year. Increasing the iterations stopped the sagging, though it also reduce my FPS to 1/10 but thats another problem that I can fix

**Comment by liabru** [comment]
@FieryLionite That's probably too many iterations for real time (a value like `10` for each is probably about right). Maybe try these ideas:

- use multiple constraint links on each rather than one
- use pin constraints (zero length)
- increase `stiffness` (it can even go a little above `1`)
- lower the mass of each body so that the ones near the bottom are less than at the top
- multiple `Engine.updates` per step with a fixed `delta` (@nasenfloete)
