### ISSUE TITLE
How to avoid vertical friction with static bodies

### ISSUE THREAD

**Issue by jaloplo** [liabru/matter-js#694]
I'm developing a simple game and creating some static objects for world boundaries. I also have a body as a player that I move across the scene from the left to the right and jump reaching some platforms. Yes, another platform game but for demo purposes. Everything seems to be normal but when the player falls down and collide with a wall friction doesn't allow gravity to appear. It is something very strange, I suppose I should have the same behavior with floor items but they work as expected and the player goes from one side to the other without any friction.

Here is the player configuration:
```
Bodies.rectangle(50, 100, 32, 32, { inertia: Infinity });
```

And here for the left wall:

```
Bodies.rectangle(x, y + 8, 2, 16, { isStatic: true })
```

How can I avoid that friction when jumping and falling down?

**Comment by jaloplo** [comment]
Hi guys,

I've found why is this happening but not the solution. If you set "inertia" to Infinity value to a box it will have friction with other boxes sides. The following jsFiddle shows it. Do you know how to avoid this behavior? Am I doing something wrong or missed something?

[Matter.js vertical friction test link](https://jsfiddle.net/jaloplo/Lkzh3sfv/)

Regards.

**Comment by Tommsy64** [comment]
I've ran into the same issue. Michael Hadley solves this issue (which he calls spiderman-ing) in this [tutorial](https://itnext.io/modular-game-worlds-in-phaser-3-tilemaps-5-matter-physics-platformer-d14d1f614557) by attaching two additional sensor collision boxes to the left and right of the main collision box. When the sensor collision box collides with something, the main body is moved such that it does not collide but the sensor still collides. This effectively avoids the vertical friction.

However, this seems more like a work-around then an actual solution to the problem...

**Comment by nullobject** [comment]
I have exactly the same issue.

**Comment by liabru** [comment]
Any bodies that are in contact will have friction between them, it doesn't matter what the orientation is, so you'll need to add some custom logic for this. I think one solution for this is to use a thin sensor at the player's 'feet' that turns the player's `body.friction` on only when it is in collision with a 'ground' body, but the sensor should not overlap the left and right edges of the player, only the bottom edge. 

It's almost possible to use compound body parts to do this, but unfortunately they don't allow for different friction values per-part (you could maybe try patch this in [Pair.update](https://github.com/liabru/matter-js/blob/master/src/collision/Pair.js#L64-L68) to use `bodyA` rather than `parentA` etc, it might work).

> Setting friction to zero on a static body still applies friction to any colliding bodies.

Try setting the friction again after the static body creation, because by default static bodies have their friction set to `1`.

**Comment by b3nk4n** [comment]
> Try setting the friction again after the static body creation, because by default static bodies have their friction set to 1.

Wow, I went through the whole [docs](https://brm.io/matter-js/docs/classes/Body.html#property_friction), some other Issues of this repo, or tried to implement my own workarounds such as trying to compose multiple bodies with different physical properties to achieve something rather simple:
- In a basic jump'n'run platformer example, not having the player kind of "sticking" to the wall (and having friction applied) on the world boundaries left and right using static bodies.
  - and also **note that the player body has `inertia: Infinity` applied to prevent body rotation** to have it behaving more "arcade" style

My initial thought was that when one of both player or wall has set `friction: 0`, then there should be effectively no friction. However this did not work, and the player was always sliding down the walls very slowly.

In the end, the above comment solved my problem. It seems like the explicit `friction` option is simply ignored for static bodies:
```javascript
Matter.Bodies.rectangle(..., {
  isStatic: true,
  friction: 0 // <-- this is ignored!!!
})
```

This can be easily confirmed with the following snipped:

```javascript
const dynamicBody = Matter.Bodies.rectangle(0, 0, 32, 32, {
  friction: 0
});
const staticBody = Matter.Bodies.rectangle(0, 0, 32, 32, {
  isStatic: true,
  friction: 0
});

console.log({
  staticFriction: staticBody.friction,
  dynamicFriction: dynamicBody.friction
})
```
With output: `{"staticFriction": 1,"dynamicFriction": 0}`

##- Solution:
As mentioned above, if one **really** wants to set the `friction` of a static body, then this needs to be set **after** body creation:
```
const staticBody = Matter.Bodies.rectangle(0, 0, 32, 32, {
  isStatic: true,
  // friction: 0 needs to be set after body creation to effectively be applied
});
staticBody.friction = 0

console.log({
  staticFriction: staticBody.friction
})
```
With finally the desired outcome: `{"dynamicFriction": 1}`, as well as the desired effect that the player is not "sticking" to the wall anymore by having friction applied.


### Follow-up question

Personally, I don't understand why the user defined `friction` option is simply ignored for static bodies. Is there any particular reason @liabru ? 😇 
As a user of this library, I have the perception that this is a bug. Because if there would be a real reason to not allow any other `friction` value for static bodies, then setting it after body creation should also not be allowed.
Looking forward to your reply!

(And thx for this great project! ❤️ )
