### ISSUE TITLE
Please update releases page

### ISSUE THREAD

**Issue by vck3000** [liabru/matter-js#697]
I was trying to get revolute joints to work by following #139 and could not get it to work because I only just now realised I was using the "stable" 0.10.0 version. This is seen to new people under "Install" -> "get a stable release". Please update this to show the latest stable version. 

The demos also use a version above 0.10.0. I only realised I was using an outdated version because I was trying to duplicate the double pendulum example and realised that Render.startViewTransform was not defined, despite it being in the docs. 

Thank you!

**Comment by liabru** [comment]
Apologies for the confusion, I have revisited this and have switched to using only tags rather than creating entries for the github releases page, as you can now see on the [releases](https://github.com/liabru/matter-js/releases) section which now matches that on [npm](https://www.npmjs.com/package/matter-js?activeTab=versions).

**Comment by vck3000** [comment]
Thank you!
