### ISSUE TITLE
Physics changes when dealing with small Bodies

### ISSUE THREAD

**Issue by amorygalili** [liabru/matter-js#701]
Hello,

I'm running into an issue where the physics in matter-js seems to change when working with bodies at a small scale. I'm working on a small scale because I'm creating a 2d physics simulator to control a simple robot, which requires users to enter lengths in ft and velocities in ft/s. These robots are about 2ft long, but in matter they're really 2px long:

```javascript
let robot = Bodies.rectangle(0, 0, 2, 2);
World.add(engine.world, [robot]);
```

I have a config property called pixelsPerFoot, which is passed into the pixelRatio option. A typical value passed into pixelsPerFoot/pixelRatio would be 20. Here's an example created in Plunker which demonstrates the issue: http://plnkr.co/TfBFtE0tXh1tTtKkILgk?p=preview

You can control the "robot" with the wasd keys.

In the plunker I'm setting a variable pr (pixel ratio) to 60. The value is this high so the changes in physics is more clear. With a low value the physics seems to work as expected, but with a high value bodies seem to intersect, stick to each other, and interact in weird ways when they collide. Is there a reason for this? Maybe it has to do with a loss of precision?

An alternative solution is to force users to multiply everything by the pixelsPerFoot constant, but I really I don't want to force users to write code that looks like this:

```javascript
let robot = Bodies.rectangle(
  config.robot.width / 2 * this.pxPerFt,
  config.robot.height / 2 * this.pxPerFt, 
  config.robot.width * this.pxPerFt,
  config.robot.height * this.pxPerFt
);
```

Is there a way around this issue? Is there some other way to set the units in matter-js to something other than pixels?

**Comment by liabru** [comment]
The built in renderer by default renders the unit value of `1` at `1px` but there's no reason for that other than convenience, if you want to render at a different scale, then you should just change the size of `render.bounds` (not `render.pixelRatio` that's intended for high DPI screens). See the [Views example](http://brm.io/matter-js/demo/#views) and scroll on the canvas, which changes the scale of rendering by making the bounds smaller or larger.

Now that said, in practice using very small bodies will cause problems, because the engine has certain optimisations that are tuned for bodies assuming a size of at least `10`. One of these for example is [body.slop](http://brm.io/matter-js/docs/classes/Body.html#property_slop) that can be changed, but there are others you'd need to change.

My suggestion instead is to both use a larger scale factor when creating your bodies (e.g. `Bodies.rectangle(0, 0, 2 * 10, 2 * 10)` and also scale your rendering to get the display size you need, hope that makes sense.
