### ISSUE TITLE
UNSTRETCHABLE rope by using rope-segments and constraints ?

### ISSUE THREAD

**Issue by dibyendu** [liabru/matter-js#709]
Hi, I was trying to build a world with 2 bodies connected by an UNSTRETCHABLE rope hanging over a pulley. I've seen an issue (#396) where you've mentioned it to be a rigid-body engine and thus getting a rope in 1 piece is not possible.

Therefor I've broken it into pieces by means of rectangles(rope segments) which are connected by constraints.

But I can not get rid of the stretchability property of the rope/string. I've tried putting `mass = 0` for the rope-segments and/or `stiffness = 1` for the constraints. But nothing seems to work properly. It behaves more like a rubber band. Something similar to #706

Here is what I've done: https://jsbin.com/nosujohaco/1/edit?js,output

Any suggestion is highly appreciated.

**Comment by liabru** [comment]
I think the mass difference is too great, try increasing the the mass / size of your rope segment bodies e.g. `{ density: 0.2 }`, then it seems to work? Also you should probably increase `engine.constraintIterations` to make them even stiffer and you can also try double up the constraints i.e. two at each point rather than one.

**Comment by liabru** [comment]
See also my response in https://github.com/liabru/matter-js/issues/682#issuecomment-499077009 for other ways to improve this.
