### ISSUE TITLE
How can I draw simple lines as grid on the background ?

### ISSUE THREAD

**Issue by abachi** [liabru/matter-js#711]
Hello,
Thank you for this wonderful project.
I want to draw simple lines as a grid in the background, is there any way to use `render.context` to draw lines and inject it to the game loop so it keeps rendering?
I can use rectangles and collision filtering to achieve that but I don't think it is a good solution.

**Comment by GithubUsername123456789** [comment]
I don't think you need Matter.js for this... What's wrong with just drawing lines to the canvas before rendering?

**Comment by liabru** [comment]
Yeah it's advised to handle your own rendering for specific needs, but if you just want to add something like this into the debug renderer, you could maybe set the background to be transparent, then in the renderer's `beforeRender` or `afterRender` event use `render.context` to draw what you need? Otherwise, make a copy of the debug renderer code and edit it as you need.
