### ISSUE TITLE
Issues scaling bodies along with their sprites

### ISSUE THREAD

**Issue by chrysb** [liabru/matter-js#760]
I am scaling a body up by 1.5, and then back down to its original size. I'm doing this using a parametric animation, meaning I'm compounding the scale of the body until it exceeds a certain scale and then I stop the animation and set the scale to the target scale.

The problem is, I have to scale both the sprite and the actual body itself separately. The sprite has absolute `xScale` and `yScale` values which makes it easy to detect when the desired scale has been reached. The body does not have any such absolute value. The closest thing I've found is `area`.  At the end of the animation, I attempt to calculate the difference between the `startingArea` and the `currentArea` and determine a final value to scale the body by to reach the original size, but unfortunately it doesn't work reliably.

Is there a way to access the absolute scale value of body? Am I missing something obvious?

Thanks!

**Comment by RichardPoole42** [comment]
Body.scale doesn't remember the original characteristics of the body; it just scales the vertices and adjusts the other properties of the body (mass, area, and so on) accordingly. So there is nothing obvious you're missing; there just isn't any such concept, internally, as the absolute scale of a body.

Having said that, using the area should work pretty well (not necessarily exactly, of course, as nothing is exact in a floating-point world) so it would be interesting to know how that is failing to work for you, especially if there's some particular situation or shape of body that makes it fail.

**Comment by chrysb** [comment]
Thanks @RichardPoole42 !

It's not failing badly, it's just slightly off, so sometimes the body is either slightly smaller or larger than the sprite. So the problem is less so about the inconsistent scaling between bodies, but more the inconsistent scaling between the sprite and the bodies.

You can see the demo here: http://chrysbader.com

**Comment by RichardPoole42** [comment]
I can't see any scale problems in the demo - maybe the problem is specific to some environments, or maybe it's happening but everything's so close to being correct that I just don't notice. I have looked, though. If, after you've done the final scaling which should get you back to where you started, you read the area again, how close is it to the value you want?

**Comment by chrysb** [comment]
It's pretty small, and maybe I'm a bit of a perfectionist, but in this image you can see the distance between the "floor" and the icons is slightly different after they've scaled back down.

![image](https://user-images.githubusercontent.com/120388/60836838-7192b480-a17b-11e9-89d3-e066d5af9483.png)

**Comment by liabru** [comment]
Exactly, there's no concept of scale in the physics engine like there is with a rendering engine. The `Vertices.scale` function literally rescales the geometry in place, so you need to manage updating the sprite scale yourself. Probably the easiest way is to create a function that applies `Vertices.scale` and updates the sprite scale simultaneously, rather than trying to figure out the scale factor.
