### ISSUE TITLE
Support for ignoring gravity on specific bodies

### ISSUE THREAD

**Issue by mobileben** [liabru/matter-js#765]
Are there any plans to do this? The change seems rather innocuous to do. It seems that if a Body has a property to do this, then `Engine._bodiesApplyGravity` can simply just skip that body.

I guess the only drawback I can see right now is extra data size for the flag and some processing time to read the flag.

In my case the application is to make "floating" targets which eventually move (hence why they can't be static).

**Comment by mobileben** [comment]
As an FYI, Phaser does do this in their version of matter.js

https://github.com/photonstorm/phaser/blob/cb49d8909b4b3f8ba8f1a94e2bcd5c17a614bff6/src/physics/matter-js/lib/core/Engine.js#L310
https://github.com/photonstorm/phaser/blob/cb49d8909b4b3f8ba8f1a94e2bcd5c17a614bff6/src/physics/matter-js/lib/body/Body.js#L62

**Comment by liabru** [comment]
I think this definitely more of a feature for a game engine rather than the physics engine itself.

The built in gravity is really just there as a helper, if you need specific mechanics it's really best to disable it and apply your own however you need (it's easier than it might seem too).

For a simple gravity force effect just loop through your bodies and do something like 
`Body.applyForce(body, { x: body.mass * gravity.x, y: body.mass * gravity.y })`
where `gravity` is a vector with direction and scale of your gravity constant.

**Comment by alisrn** [comment]
I think applyForce function is improved and gets another argument. Above doesn't work since it doesn't pass position argument.
`Body.applyForce = function(body, position, force)`
