### ISSUE TITLE
Vertices stroke having odd results

### ISSUE THREAD

**Issue by richgcook** [liabru/matter-js#779]
Is there a way, when applying stroke, it adheres to the path points? It seems to join across points and sometimes extend further than where the point ends?

![Screenshot 2019-09-25 at 17 31 45](https://user-images.githubusercontent.com/901289/65620818-6dc44080-dfba-11e9-9c8a-4de5b6bfb005.jpg)

I copied the simple Concave demo to replicate this issue: https://codepen.io/johnthepainter/pen/YzKgvpL

**Comment by liabru** [comment]
Thick strokes are not straightforward to render correctly in a lot of cases, ideally I think you'd need some custom stroke alignment which canvas probably doesn't have, but check out the docs for HTML canvas context [lineJoin](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin) and [miterLimit](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/miterLimit) properties, they might help a bit here.

You can probably set them after creating a renderer like this `render.context.lineJoin = 'round'` and `render.context.miterLimit = 1`, I think they will persist but if not you may need to use a render event or patch a function somewhere.

Also another part of the problem is that you're rendering the body parts individually (which seem to have very sharp corners) rather than only the outer edges, which you can do by setting `render.options.showInternalEdges = false`.
