### ISSUE TITLE
can I change the fps of the engine

### ISSUE THREAD

**Issue by elcarim5efil** [liabru/matter-js#79]
I try to change the _fps in matter.js to 30, theoretically, the _delta gets larger, but in fact, the engine seems to run faster.
Did I do wrong? Is there anyother way to limit the fps to a lower value?

**Comment by liabru** [comment]
There's currently no support for this in the built in runner, but it's possible if you create your own runner (which is highly recommended, see [the wiki](https://github.com/liabru/matter-js/wiki/Rendering#using-a-custom-game-loop)).

I've experimented with it, but can't find a use case where you'd want less than 60fps.
Is it for performance reasons?

Because if you're using < 60fps for physics, you will need to start doing extra iterations (e.g. 2x per frame at 30fps) to maintain the same accuracy and stability (i.e. you won't gain any performance except a little from the reduced amount of rendering).

**Comment by elcarim5efil** [comment]
thank you for you response, and I will try out you suggestion. In fact, I've found that sometimes the framerate is not stable when the bodies are moving fast with image rendering. Thank you for your response again, and also thank you for you wonderful work!

**Comment by wmike1987** [comment]
Are you sure requestAnimationFrame is locked at 60? The mozilla docs state

> The number of callbacks is usually 60 times per second, but will generally match the display refresh rate in most web browsers as per W3C recommendation.

**Comment by liabru** [comment]
Yeah that's true it does depend on the monitor refresh rate, but what I meant was you can't directly set a custom fps from code on the browser. It is however possible to use a lower refresh rate by frame skipping, but that comes with its own set of issues too.

**Comment by wmike1987** [comment]
One catch I've encountered is that the default implementation of Runner sets the fps to 60 and a deltaMax and deltaMin are based on this. I had users with 144hz monitors whose simulations would run fast because the smallest delta (deltaMin) Runner would comprehend was 16ms, but it was happening a lot more than 60 times a second.

Is there a reason to even specify an fps in Runner if it can vary due to the monitor refresh rate?

**Comment by lafkpages** [comment]
> I had users with 144hz monitors whose simulations would run fast

same #1152
