### ISSUE TITLE
Can objects float in a world?

### ISSUE THREAD

**Issue by joshmutus** [liabru/matter-js#793]
I noticed that density is a parameters and I want to make objects that float, however I cannot figure out how to assign a global density to the world - only to objects. 

I noticed I could set reverse gravity, but I only want some objects to float, not all of them.

**Comment by rvanderspuy** [comment]
I've actually just worked on this problem. I kind of cheated, because I used a simple tween with setPostion to make floating items float to the top of the water plane. (The water plane is just an arbitrary Y value.) Here's what my code looks like:
```
let applyBouyancy = body => {
        let waterPlaneY = 100;
        let vy = body.position.y - waterPlaneY;
        let distanceBetweenBodyAndWaterPlane = Math.sqrt(vy * vy);
        let force = 0.000008;
        if (distanceBetweenBodyAndWaterPlane < 100) {
          body.timeScale = 1;
        } else {
         body.timeScale = 0.2;
       }
        MATTER.Body.applyForce(body, body.position, {
          x: 0,
          y: -distanceBetweenBodyAndWaterPlane * force //-0.0007//-0.00055
        });
      };

      if (this.bodiesInWater.length > 0) {
        this.bodiesInWater.forEach(body => {
          //Make the floating items float
          if (body.canFloat) {
            applyBouyancy(body);
          }
        });
      }
```
The other trick was that I used the `body.timeScale` property to slow the bodies down when they are in the water, to simulate viscosity.

It's not a perfect simulation, but it looks quite realistic and is good enough for my needs at the moment.

**Comment by joshmutus** [comment]
That's neat! 
Since density is a simulation parameter, what is it used for? Just collisions with other bodies? 
Have you tried changing the air resistance of the bodies for viscosity?

**Comment by rvanderspuy** [comment]
Air resistance might work too... I didn't think of that! 😄 

Yes, changing density could work. I just ran into a complex situation where it was difficult to control floating/sinking of each body because their densities varied with their size. So large plastics that should float would sink, and small metals that should sink, would float. With a bit more time I'm sure I could fine-tune an accurate simulation, but I found just giving all the bodies the same mass, regardless of size, produces very consistent results. Not accurate, but easy and it works.

**Comment by joshmutus** [comment]
I modified your solution to simply apply a small force to each bubble that I tuned it so they're just a little buoyant. I also applied air resistance and it looks pretty convincing I think. 
```typescript
let circ = matter.Bodies.circle(
      this.box.position.x,
      this.box.position.y,
      40,
      { frictionAir: .05 }
    );
  matter.Events.on(this.engine, "beforeUpdate", ()=>{
      matter.Body.applyForce(circ, circ.position, { x: 0, y: -0.0015*4 });
    });
```
