### ISSUE TITLE
When the block rotates, it enters other blocks and abruptly jumps. How to fix?

### ISSUE THREAD

**Issue by IlyaKB** [liabru/matter-js#798]
During rotation, the block runs into two static blocks side by side and at a certain moment jumps sharply from them. How to prevent collisions and sudden jumps?

Details with an example here: [stackoverflow.com/questions/1048544](https://ru.stackoverflow.com/questions/1048544/matter-js-%d0%bf%d1%80%d0%b8-%d0%b2%d1%80%d0%b0%d1%89%d0%b5%d0%bd%d0%b8%d0%b8-%d0%b1%d0%bb%d0%be%d0%ba%d0%b0-%d0%be%d0%bd-%d0%b7%d0%b0%d0%b5%d0%b7%d0%b6%d0%b0%d0%b5%d1%82-%d0%bd%d0%b0-%d0%b4%d1%80%d1%83%d0%b3%d0%b8%d0%b5-%d0%b1%d0%bb%d0%be%d0%ba%d0%b8-%d0%b8-%d1%80%d0%b5%d0%b7%d0%ba%d0%be-%d0%be%d1%82%d0%bf%d1%80%d1%8b%d0%b3%d0%b8%d0%b2%d0%b0%d0%b5%d1%82-%d0%b1%d0%b0)

**Comment by liabru** [comment]
I think the issue is you're applying rotation without updating the angular velocity (which is needed for a correct response in this case), see the [body manipulation](https://brm.io/matter-js/demo/#manipulation) example and [source](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js#L90-L93).

**Comment by IlyaKB** [comment]
> I think the issue is you're applying rotation without updating the angular velocity (which is needed for a correct response in this case), see the [body manipulation](https://brm.io/matter-js/demo/#manipulation) example and [source](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js#L90-L93).

Using the "setAngularVelocity" method instead of the "rotate" method does not change the situation! ((The body still drives through the blocks and jumps out! Demo: [https://jsfiddle.net/wcuzax5p/](https://jsfiddle.net/wcuzax5p/)

**Comment by liabru** [comment]
I think really you'd need to prevent the player turning too far in this situation, so they can't get into a deep collision. One idea is to check for collision in advance of allowing turning.

Level design would help here, make sure any gaps in the environment are either larger than the length of the tank, or smaller than the width of the tank, so that it can't get stuck.
