### ISSUE TITLE
normal values are inconsistent

### ISSUE THREAD

**Issue by marcusx2** [liabru/matter-js#811]
I have two bodies. Think of a player, and a platform. The player jumps on the platform. The collision normal sometimes is {x: 0, y: 1} and sometimes it's {x: -0, y: -1}. It seems that it varies depending on the size of the platform, and the distance from the player before it jumps to the platform.  This screws up my logic, wtf are the normals varying? I am not changing the rotation of any body. The player is always touching the platform from above, but the normals are not consistent.

**Comment by liabru** [comment]
It's possible that the normal might flip (performance reasons, sorry) because it's always facing away from the 'reference body' of the collision (stored in `collision.bodyA`, I think).

So what you should do is calculate an adjusted normal that is always facing towards from your player instead. An example of how to do this is [here](https://github.com/liabru/matter-js/blob/master/src/collision/SAT.js#L103-L114).
