### ISSUE TITLE
How do I run the Engine on the server, then get the data to client

### ISSUE THREAD

**Issue by holoverse** [liabru/matter-js#847]
I have a server running the engine, and its working just fine.
Now, I need to know how to pass the data to the connected clients.

What is the best way to do this??
When I try serializing the engine, and sending through WebSockets, my app crashes, and says call stack size exceeded.

Please let me know how I can render the physics happening on the server, onto a canvas for the client.

**Comment by liabru** [comment]
Try only sending actions (e.g. `create body type A at x, y`) and changes (e.g. `body.position`) over the network and replay them on the client, rather than all of the state at once.

**Comment by jransome** [comment]
What apis can we use to 'replay' these actions on the client engine @liabru? 

I can understand how we might replay user input, but what about all the movements/collisions etc. computed by the server side engine? how do those get registered with the client side engine?

**Comment by codylico** [comment]
Just an idea, feel free to ignore:

Maybe there's no client-side engine? Let the server handle the collision logic, then the client just presents the positions to the user.

**Comment by holoverse** [comment]
Yeah that's exactly what I want to do.  But then i cant get the positions/world back to client.

Because if i serialized the whole engine and send over websockets every 10ms or so.  
1. Its huge and would run into performance issues when multiple users are in the game.  2. It gives an error as mentioned at the beginning of this thread.  A recursive stack error. I cant get the world to the client.

That is my whole problem.  So your idea is exactly my idea as well. Just...   how

**Comment by codylico** [comment]
I would not expect to need to send the whole world back to the client, just the parts that change between frames. Things like player positions, items, and such.

Something like a brick wall need not be sent.

So the client would start with a full copy of the world, but then only players and items that change would be updated each frame, that way you need not serialize the whole engine. You may need some extra logic to discern which moves and which doesn't.

**Comment by liabru** [comment]
Exactly, detect what has changed and send only that, or better yet only send high level actions specific to your game, making sure the effects are fully deterministic, including the time they occurred so you can replay them. That's all out of the scope of this library though, it's more something a game engine should handle.

Depending on what type of gameplay you need though, an efficient way to do a simple one-way remote renderer might be to only send the changes in velocity (the acceleration), since this doesn't change often in many types of game, even when it does it can still often be simulated as a single action (e.g. 'gear changed up'). You will still need to use occasional position keyframes to avoid drift (or just send position too when ever you send acceleration), using some interpolation to smooth out the synchronisation updates to avoid visible jumps. If lag is a problem, you'll also need to do some forward prediction based on latency. It's a complex topic!
