### ISSUE TITLE
bug: chain shakes when dragged

### ISSUE THREAD

**Issue by hcapp01** [liabru/matter-js#853]
Drag the chain from about 1/5 length. Segments shakes. See gif below.
https://codepen.io/hcapp01/pen/BaojBbN
![2020-04-14_22-42-28](https://user-images.githubusercontent.com/3634644/79302641-d06f2200-7ea1-11ea-9202-7c8687f547eb.gif)

**Comment by liabru** [comment]
It looks like instability due to over extension of those constraints, so I'd suggest maybe increasing their length and decreasing stiffness, possibly only when they are detected to be over a certain length. You could also try same thing with the mouse constraint instead so the chain appears to remain stiff.
