### ISSUE TITLE
Struggling with vector offestting

### ISSUE THREAD

**Issue by RaziHaj** [liabru/matter-js#876]
Hi!

I'm trying to animate a floating bottle in the water. I was planning on figuring out the basic physics with a rectangle and then building upon it.

I'm having problems offsetting the canvas fillRect() (which is drawn from top-left), and the rectangle from matter.js (which is drawn from the center point). I have looked at all the answers from previous posts, especially tread [#211](https://github.com/liabru/matter-js/issues/211), but I still have a hard time figuring what to do. 

I've tried to add this line after creating my rectangle, but it seems to make things worse:
`Matter.Body.translate(this.body, Matter.Vector.sub(this.body.bounds.min, this.body.position));`

I'm not sure what I'm lacking: knowledge about how to calculate this position with vectors, where to use translate, or something else.

I've made a clean code example [here](https://playcode.io/605704) to demonstrate my problem. You can spawn objects by clicking on the screen. The bottle.js is the file where I tried to solve the problem.

If this is too cumbersome, I would love to know at least where to look for answers.

Thank you for your time!

**Comment by liabru** [comment]
So rather than taking this approach, I'd strongly suggest rendering the `body.vertices` instead as you can see in the wiki page on [rendering](https://github.com/liabru/matter-js/wiki/Rendering`). This is much easier since the vertices are already in world-space and you won't need to apply any transforms, hope that helps.
