### ISSUE TITLE
npm run doc fails.

### ISSUE THREAD

**Issue by cbuteau** [liabru/matter-js#878]
Hello,

I saw that you need documentation of readonly tags.

https://github.com/liabru/matter-js/issues/596

I cloned the repository.
I ran npm install

When I ran 
npm run doc
It ran into errors because I did not have yuidoc.
So I installed yuidoc.

npm -g install yuidocjs

Now when I run it I run into this error.
error: Error: ENOENT: no such file or directory, open 'E:\Repos\matter-js\doc\build\data.json'

I also can't get the lint to run which you want run if people contribute.

npm install -g eslint

npm run lint
No files matching the pattern "'src/**/*.js'" were found.
Please check for typing mistakes in the pattern.

So I am stopping even though the dev server runs fine.
I was going to start small on your lovely library and then maybe do a feature or bug after I did some doc work.

Let me know if there is something else you would want me to work on instead of the @readonly request.

**Comment by liabru** [comment]
On the docs build, I imagine the issue is probably that the custom theme isn't currently included in the repo? You may have to set some option to use one of the built in themes if you just need to review, otherwise I'm happy to review docs changes when I build them.

As for the linter, that should be working so I'll need to review this a bit further.
