### ISSUE TITLE
Stuttering bounds update on scroll

### ISSUE THREAD

**Issue by David-Gallimore** [liabru/matter-js#880]
Hi there,

I have a large scene that spans the whole length of my page (over 6000px tall).

Instead of having a canvas this tall which doesn't perform very well with some browsers I want to have a canvas that is the height of the browser and then update the  Bounds depending on scroll position:

`Bounds.shift(matterRender.bounds, { x: 0, y: $(window).scrollTop()});`

I've tried triggering this with both `$(window).scroll` and `Matter.Events.on(engine, 'afterUpdate', function(event) { } );`

But still stutters well below the FPS. Any ideas/tips would be greatly appreciated.

Thanks

David

**Comment by liabru** [comment]
It sounds like you have the right approach, it's possible that it's down to handling of the scroll input. This is out of scope for an issue here but you'll want to look into both [Passive Event Listeners](https://developers.google.com/web/updates/2016/06/passive-event-listeners) and combining this with `requestAnimationFrame` to debounce since they can be called at a very high rate. You'll probably also want to smooth out the scroll values too by tweening / interpolating them.
