### ISSUE TITLE
Matter js frame drops with polygon colliders

### ISSUE THREAD

**Issue by MeenakshiKathiresan** [liabru/matter-js#883]
I am building a game with polygon colliders. I am creating over 30 colliders in the start of the game and reusing them. The game fps drops to over 30-40 in the first 10 seconds and picks up to be eventually smooth. When I remove the colliders, it runs on 60fps from the start. What could be the issue?
Ps- I have already tried scaling the game down so that physics calculations are easier. It helped but not enough I guess.

**Comment by liabru** [comment]
Without seeing any code, I don't think I can help much other than suggesting that you try [profiling your code](https://developers.google.com/web/tools/chrome-devtools/rendering-tools/js-execution) in the browser to try find the expensive parts. Otherwise please provide some code / more information on your process, thanks.
