### ISSUE TITLE
Removed object is still visible

### ISSUE THREAD

**Issue by soniaac** [liabru/matter-js#918]
I'm trying to make a game where I delete a coin when the player collides with it, but the coin isn't disappearing after I remove it. After deletion, the coin doesn't collide with anything anymore, and the world.bodies.length count goes down, but it's still visible! 
I've also tried scaling its radius down by 0.01 and setting its visible property to false, but it still won't disappear. 

Not sure if it's relevant, but I'm using React Native & Expo, and it's a mobile app.  Any help would be greatly appreciated! 

![image](https://user-images.githubusercontent.com/70602671/93937817-549dbf00-fcf6-11ea-9df8-b755e77f9ce8.png)

**Comment by TinyRobot19** [comment]
Matter.World.remove takes a world as its first parameter. Try this: `Matter.World.remove(engine.world, coin);` Check the [docs](https://brm.io/matter-js/docs/classes/World.html) for information on methods and parameters.

**Comment by soniaac** [comment]
I still run into the same issue... the body will pass through the coin, and if I log world.bodies.length, it goes down, but the coin still renders on the screen.

Maybe it's an issue of not re-rendering properly after deletion? I'm not using matter.js's Render(); because it seems to only support HTML games, not actual mobile apps.
Or maybe I need to save Matter.World.Render as a state and update that after deletion?

Any insight would be greatly appreciated!

**Comment by soniaac** [comment]
I ended up just moving the coin off the screen to imitate disappearing, but that's not super elegant I guess... if anyone has better ideas it'd be really appreciated!

**Comment by skeddles** [comment]
What i found from other threads was `Matter.Composite.remove(engine.world, BODY);`

**Comment by liabru** [comment]
As @TinyRobot19 and @skeddles mentioned, I think you need to pass the world before the body as shown in their comments above, also see the docs for [Composite.remove](https://brm.io/matter-js/docs/classes/Composite.html#method_remove).

If that doesn't do the trick, try store the `body.id` of the bodies to be removed but instead remove them at the end of the update instead of in the collision event loop, e.g. in the engine `afterUpdate` event. If that doesn't work then maybe this is something to investigate further.

**Comment by patrick-cobbled445** [comment]
Solved it myself https://lnkr.fun/de740f9
