### ISSUE TITLE
How to enable the ability to scroll a page with Matter.js?

### ISSUE THREAD

**Issue by didacus** [liabru/matter-js#929]
I want to enable scrolling in a page that contains a Matter.js canvas. I have found and tried a few solutions such as removingEventListener without success. I created a post on StackOverflow but no luck with answers. Therefore I decided to come directly to the source of knowledge.

How can I enable page scrolling in a page with Matter.js?  Thank you in advance.

Here's the [Codepen](https://codesandbox.io/s/scrolling-event-253k4?file=/index.html) and the [post](https://stackoverflow.com/questions/64486564/matter-js-how-to-prevent-mouseconstraint-to-capture-scroll-events).

```
// Why is this not working?
mouseConstraint.mouse.element.removeEventListener(
  "mousewheel",
  mouseConstraint.mouse.mousewheel
);
mouseConstraint.mouse.element.removeEventListener(
  "DOMMouseScroll",
  mouseConstraint.mouse.mousewheel
);
```

**Comment by bouraqadi** [comment]
The answer is provided by Xander Gottlieb in a blog post along with many other tips [Matter.js— The Missing Tutorial](https://blog.alexandergottlieb.com/matter-js-the-missing-tutorial-70aafc06b167). 

By default, `MouseConstraint` captures scroll events. The following snippet fixes it.
```
mouseConstraint.mouse.element.removeEventListener("mousewheel", mouseConstraint.mouse.mousewheel);
mouseConstraint.mouse.element.removeEventListener("DOMMouseScroll", mouseConstraint.mouse.mousewheel);
```

**Comment by didacus** [comment]
@bouraqadi thank you for your reply.

I don't think you had a look into the CodeSandbox I shared. I am using that snippet and the scroll still not working. The article was the first I tried without success. I am unsure if I am adding to in the wrong place. Could you perhaps have a look into the code and tell me if something is out of place regarding the snippet?

Thank you in advance.

**Comment by bouraqadi** [comment]
In your HTML the  the `overflow` should be set to `scroll`

**Comment by didacus** [comment]
@bouraqadi indeed you are correct. Thank you for your help.

**Comment by liabru** [comment]
Yeah I think you may need to do something like the above, otherwise consider switching to your own input handling and rendering to get the control you need.

**Comment by ayank007** [comment]
I'm still unable to solve the problem in touch screen devices.

**Comment by Striffly** [comment]
@ayank007 I give a potential fix here : https://github.com/liabru/matter-js/issues/678#issuecomment-1371233031

**Comment by bhuvarloka** [comment]
This issue have been haunting me since a few days and I have tried the methods mentioned without success, maybe something related to the version. At certain point I realized that interacting with the canvas while scrolling is impractical - despite would be nice.

Having this in mind  I could improvise one solution that temporarily disables the interaction during scrolling.  It is not perfect, but it worked so far for my case. 

```
let scrollTimeout;
function handleScroll() {
  render.canvas.style.pointerEvents = "none";
  clearTimeout(scrollTimeout);
  scrollTimeout = setTimeout(() => {
    render.canvas.style.pointerEvents = "auto";
  }, 200);
}
  
 render.canvas.addEventListener("wheel", handleScroll);
```

**Comment by animatedcreativity** [comment]
@colorful-invisible Thank you so much for saving my time.

**Comment by fokichev** [comment]
Indirectly mentioned by @colorful-invisible, but I think the name of listener changed from 'mousewheel' to 'wheel' since that article's writing. So now this works for me:
`mouseConstraint.mouse.element.removeEventListener("wheel", mouseConstraint.mouse.mousewheel);`
(or if mouse initiated, just) `mouse.element.removeEventListener("wheel", mouse.mousewheel);`

but this doesn't:
`mouseConstraint.mouse.element.removeEventListener("mousewheel", mouseConstraint.mouse.mousewheel);` (or "DOMMouseScroll")

**Comment by bhuvarloka** [comment]
That's great. Thanks a lot.

**Comment by ivshiryaev** [comment]
@fokichev you saved my life 🔥

**Comment by ABRO-515** [comment]
@fokichev  this worked for me bro. Loved it ❤

**Comment by SzymZem** [comment]
If anyone else couldn't scroll after dragging, I fixed it by setting the CSS `touch-action` to `none`
