### ISSUE TITLE
Creating additonal Body (text letters)

### ISSUE THREAD

**Issue by dpkpnm** [liabru/matter-js#94]
I really like the library and the flexibility it has for 2d engine.

I am thinking of adding a custom body factory which can take letter and show it instead of rectangle, circle and trapezoid

Is this even possible...

Deepak

**Comment by liabru** [comment]
Do you mean like in [this demo?](http://brm.io/matter-js-demo-master/#svg)

This is using the new features in the [compound-concave](https://github.com/liabru/matter-js/tree/compound-concave) branch which is due to be merged soon. In particular the text is converted from SVG, see the demo code for [Demo.svg](https://github.com/liabru/matter-js/blob/compound-concave/demo/js/Demo.js#L210-L261).

**Comment by liabru** [comment]
This feature has now been merged into master, check it out!
