### ISSUE TITLE
Unit of mass

### ISSUE THREAD

**Issue by beetrandahiya** [liabru/matter-js#942]
Hey , what is the basic unit of mass in engine. like kg or gram or lbs what?

**Comment by bouraqadi** [comment]
AFAIK there's no unit

**Comment by beetrandahiya** [comment]
then how do we calculate things, i mean, force and acceleration, how can we equate them, if we dont know what unit they are in ?

**Comment by liabru** [comment]
I'd recommend just using standard SI units (m, s, kg), but the scale is left up to you really, as that depends on your use case*. Once you define your scale for distance, time, mass you can [derive](https://en.wikipedia.org/wiki/SI_derived_unit) the scales for all the other units the usual way.

I realise this isn't all that obvious and isn't well documented though so I should probably write a wiki page on the topic, but here are roughly my thoughts as it stands. This may change in future though as I hear this question often enough it might warrant just making some default definitions in future for clarity.

As I understand it you can define your scales as you need* so long as you're _consistent throughout_. Internally the equations just consider relative dimensional units for distance, time, mass rather than assuming any absolute scale*

The default values used in `Matter.Body` are not necessarily meant to be realistic either, just tuned for stability and effect. Since this is a physics engine intended for games, as I understand it game engines will decide on an appropriate set of scales and units for their use case*

[*] okay, well there are a few caveats in practice

- recommended to scale output values and use input values in range of the defaults since they are tested
- angles are definitely radians (JS math) and the engine is tuned for time provided in milliseconds (for now)
- there are some internal module constants (for now) but most of these can be changed
- in practice some scales might be unstable due to numerical issues

**Comment by beetrandahiya** [comment]
yea, i've been working with the engine for quite some time and i make physics simulations, so , i realize that time to time i have to change the scale of my calculation so as to make them visible on the screen, and mostly scale down the realistic situation, 
like : https://codepen.io/beetran/full/mdreKEO ,here I had to divide the calculate potential energy by 35 so as to make it actually look comparable to Kinetic Energy 
and i'm working on a rocket engine simulation right now where i had to divide the exhaust force by 100 or the rocket would go wayyyyyy far 😅. 
Anyway, it works well at the end, and the final result is quite close to reality if we do some manual work.

**Comment by liabru** [comment]
Great, thanks for providing an update and glad you got it working! 

Unfortunately I don't think any single scale is going to work for everyone, the defaults are chosen for ease of use with `Matter.Render` such that a distance of `1` is `1px` on screen. 

In hindsight this probably should have been done in the renderer, using realistic values in the engine, but this was originally key to helping me visualise during the early stages of development.

**Comment by beetrandahiya** [comment]
i know its weird to ask developer of matter.js about this, but what other physics engine you prefer for the sort of physics simulations i make?

**Comment by liabru** [comment]
I think for simulations with the purpose of demonstrating exact real-world physics, often it's worth considering a specific direct implementation of those laws e.g. [pendulum formula](https://www.toppr.com/guides/physics-formulas/pendulum-formula/), as they'll likely be more accurate than a game engine would be by default.

Matter.js will hopefully simulate something that appears realistic, but in game engines accuracy will be limited for performance or ease of use, you'll need to decide if that trade off is good enough for your demonstration. 

You can often get more accurate results though by using a smaller timestep and increasing the engine iterations at the cost of performance.
