### ISSUE TITLE
Multiple Worlds/Engines randomly "freezing"

### ISSUE THREAD

**Issue by octavetoast** [liabru/matter-js#979]
I'm currently working on a multiplayer game, each server has multi-world support. For each world, I have to create a Matter `World`, `Engine`, and `Runner` (nothing in the documentation says I can run multiple `World`s with the same `Engine`).

Randomly, either the `Engine` or the `Runner` for **all** of the worlds completely stops working, freezing physics on the server-side. There is no pattern, it just happens. The problem does not resolve itself until the server is completely restarted.

For context, there are roughly 10 - 12 worlds running simultaneously per server, each world can have anywhere from 10 to 100 entities (projectiles and players) at a time.

Is there a limit to how many `Engine`s I can have running concurrently without Matter breaking?

**Comment by liabru** [comment]
In theory it should work as far as I know, it's difficult to say where the issue might be though without seeing your code and running environment. Some thoughts:

Are you using threading at all? If so make sure that you have a unique `Matter` instance per-thread. 

You should also check on the memory usage - if you have a large number of bodies make sure they are getting fully dereferenced so they can be garbage collected. If you spot a problem on that let me know.

Also I'd recommend a different approach than using `Matter.Runner` here, you should switch to just using `Engine.update` directly and use a fixed timestep, you can see a simple example on the [wiki](https://github.com/liabru/matter-js/wiki/Running).

I'd say go with one world per engine, but since a `Matter.World` is really just a `Matter.Composite`, you could experiment and compare with multiple 'worlds' in one engine, just set a collision group on each body so that they don't interact.

**Comment by octavetoast** [comment]
I fixed the issue by using a separate engine update loop from the game loop (just a `setInterval` running at 60 fps) for each world.

My game loop runs at 50ms (all worlds and entities are updated, entity update packets are sent every 50ms), but I can't seem to run `Engine.update` every 50ms, even when specifying `50` as the `delta`. The updates don't scale with the delta and the Engine move 3x faster than real-time, it only works at 60 fps.

Also, to clarify, there was no resource leakage and minimal CPU usage when using the `Runner`.

**Comment by octavetoast** [comment]
I believe the delta correction code in the `Runner` may be at fault for the breakage in my original issue. I know it's not meant for production and only for debugging, but users may rather use the `Runner` instead of their own loop considering the `Engine` doesn't seem to scale correctly based on the delta.

**Comment by liabru** [comment]
> I can't seem to run Engine.update every 50ms, even when specifying 50 as the delta

Do you have something that calls `Engine.update(engine, delta)` every `delta` ms? You need that to be exact to maintain real-time speed. Make sure engine updates are completed inside this time window (the frame budget), otherwise you need to account for that too.

One thing to note is that `delta` shouldn't be too large for accuracy reasons, in practice it should be less than `33.333` (30hz), ideally `16.666` (60hz) or less. 

Best practice is to use always use the same fixed delta value e.g. `16.666` and use multiple updates per tick if needed to catch up, check out this [article](https://www.gafferongames.com/post/fix_your_timestep/) which explains the idea.

I'm working on implementing a similar approach to this for the built in runner.

**Comment by octavetoast** [comment]
I tried using a setInterval at 50ms that calls `Engine.update(engine, 50)`, if what you're saying is correct that should work fine, but it doesn't.

Would you like me to add you to the private repo? You could take a look at the code yourself and see whats up (and possibly contribute).

**Comment by octavetoast** [comment]
Do I need to scale down my `applyForce` calls to account for `delta`?

**Comment by octavetoast** [comment]
The reason I want to use 50ms instead of ~16.6ms is because the Engine can't complete updates in the frame budget once I hit a certain amount of worlds and projectiles in a constricted environment (i.e. Node.js with a single core processor). I just want to call `Engine.update` less often without having to recalibrate my movement code.

**Comment by liabru** [comment]
> I tried using a setInterval at 50ms that calls Engine.update(engine, 50), if what you're saying is correct that should work fine, but it doesn't.

A delta of 50ms is too large to be stable normally, the highest I'd suggest is 33ms (30hz). Higher than that you should expect to see complete collision failures and janky movement, unpredictable constraints etc. 

I assume you must account for all of this in your game somehow if you've not come across those issues?

> Do I need to scale down my applyForce calls to account for delta?

Maybe this is it - unfortunately yes there is a known problem around that and there's a PR #777 that is coming to sort this out. 

Try that branch build out if you are able to, otherwise here is the [change](https://github.com/liabru/matter-js/pull/777/files#diff-f07c0103c35f743f35b6791bd898b7b0ddada0b4211256acc0f8a9ee13c9fca2R784-R789) which you could duplicate patch in directly over the existing `Matter.Body.applyForce`.

At the moment I'm working on the timing improvements to the runner before I can get back to that one - it's a slow process as it's a breaking change.

> the Engine can't complete updates in the frame budget once I hit a certain amount of worlds and projectiles in a constricted environment (i.e. Node.js with a single core processor)

Are the projectiles implemented as bodies? If you need to have say hundreds, then you should implement them using something optimised for this (e.g. ray casts).

**Comment by octavetoast** [comment]
> I assume you must account for all of this in your game somehow if you've not come across those issues?

Bodies in the world are moving nowhere near fast enough for collision failure, its just tanks moving around and running into walls and realatively slow projectiles.

**Comment by liabru** [comment]
Thanks for the link, looks to be working well and much smoother than I would expect at that delta. I see what you mean about the slow projectiles, that makes sense. Very cool.

Did my previous suggestion help you solve the remaining issue?

**Comment by octavetoast** [comment]
No, I've decided to go for 1 world per process because of the single-threaded nature of Node and the performance overhead of WebSocket connections and encoding-decoding binary messages.

I've now built the matchmaker into a cluster manager that orchestrates gameserver processes, each having one world.

**Comment by liabru** [comment]
Exactly one engine per thread sounds like the right approach to me for sure, that sounds pretty awesome!

Shall we consider this thread closed? Or can you narrow down the issue more specifically?

**Comment by octavetoast** [comment]
Nope, I think I've fixed everything. I resolved some other performance issues (like relying on getters) that had nothing to do with Matter. Thank you!
