### ISSUE TITLE
Absolute scaling of circle body

### ISSUE THREAD

**Issue by aiac** [liabru/matter-js#986]
Is there any possibility to scale circle with absolute value? `Body.scale` method is relative to current size. I have to scale it down, and then scale it back to initial size. I could do the math to reverse the scaling, but in this case the value depends on object position.

**Comment by ErrorBot1122** [comment]
you could try

```javascript
Body.scale = Body.scale;
Body.scale = posX;
```

**Comment by liabru** [comment]
Not tried it but I think you could use `body.circleRadius` like this:

```js
const scale = newRadius / body.circleRadius;
Body.scale(body, scale, scale);
```

**Comment by inear** [comment]
I also needed to scale the body, and with easing, which was to complex math for me. Solved it for any shape (single part only) by storing two copies of the vertices-array. One with the original and one with manipulated values. In the animation, gasp I'm my case. I multiply the original vertices with a scale-factor and save to the manipulated array (by index to avoid creating new arrays each frame). Then set the vertices on the body. Then finally applying rotation on the vertices to the same as the current body.angle, because body rotations are changing it's vertices.

**Comment by liabru** [comment]
One thing to know is that unlike in a graphics engine, bodies keep their own geometry absolute in world-space for performance reasons, as well as to simplify the overall implementation.

So if you need some sense of 'absolute scale' you should keep track of all scaling applied relative to the initial scale. In other words every time you scale the body using `Body.scale(body, scale, scale)`, also keep track of that by scaling a stored scale factor at the same time e.g. `body._currentScale *= scale`.

Then to revert to the original scale for example, you can do this:

```js
Body.scale(body, 1 / body._currentScale, 1 / body._currentScale);
```

**Comment by inear** [comment]
Another thing I ran into while scaling bodies by updating the vertices and applying forces at the body in the same time, was that the mass of a body changed. So the body was swept away because the minimal mass in the beginning of the scale-animation. Nothing wrong in the engine, but just a reminder if someone trying to control the scale when inserting new bodies into the world by animating them. I solved it by copying the content of the Body.setVertices-function and skipped the setMass()-call.

**Comment by liabru** [comment]
Yeah exactly definitely something to be aware of, the mass naturally changes during scaling in a physics engine but the `density` remains fixed. If you need the same mass then you will need to apply it back afterwards.

Did this help, can I consider this resolved?
