### ISSUE TITLE
Body shrinks, or is overlapped

### ISSUE THREAD

**Issue by uniquesolution29** [liabru/matter-js#992]
When I make tons of bodies, and they fall to the floor, they seem to be shrink or overlapped.

![image](https://user-images.githubusercontent.com/48445639/113525116-ca46e980-95bb-11eb-96ae-8df42a9d4824.png)

I need to make them rocks, so there must not be shrink.
Any quick hint would be appreciated!

**Comment by liabru** [comment]
When this happens you should try:

- use a [fixed timestep delta](https://brm.io/matter-js/docs/classes/Engine.html#method_update)
- increase [engine.positionIterations](https://brm.io/matter-js/docs/classes/Engine.html#property_positionIterations) and [engine.velocityIterations](https://brm.io/matter-js/docs/classes/Engine.html#property_velocityIterations)

The defaults for these settings are due to change in a coming version, but for now it's worth experimenting with them anyway to find a balance between results and performance for your usage.
